USE animadio;

CREATE TABLE GridProperty
(
    id          TINYINT     UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    property    VARCHAR(20) NOT NULL    UNIQUE
)
    ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO GridProperty
(property)
VALUES
('grid-template'),
('grid-gap'),
('place-content'),
('place-items'),
('place-self');

CREATE TABLE GridValue
(
    id      TINYINT     UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    valor   VARCHAR(30) NOT NULL    UNIQUE
)
    ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO GridValue
(valor)
VALUES
('auto/repeat(2, auto)'),
('auto/repeat(3, auto)'),
('auto/repeat(4, auto)'),
('auto/repeat(5, auto)'),
('auto/repeat(6, auto)'),
('auto/repeat(7, auto)'),
('auto/repeat(8, auto)'),
('auto/repeat(9, auto)'),
('auto/repeat(10, auto)'),
('auto/repeat(11, auto)'),
('auto/repeat(12, auto)'),
('--gap-1tn'),
('--gap-2tn'),
('--gap-3tn'),
('--gap-1sm'),
('--gap-2sm'),
('--gap-3sm'),
('--gap-1md'),
('--gap-2md'),
('--gap-3md'),
('--gap-1lg'),
('--gap-2lg'),
('--gap-3lg'),
('--gap-1wd'),
('--gap-2wd'),
('--gap-3wd'),
('space-around'),
('space-between'),
('space-evenly'),
('center'),
('stretch'),
('normal'),
('auto'),
('--place-content-start'),
('--place-content-end'),
('--place-items-base'),
('--place-items-start'),
('--place-items-end'),
('--place-self-base'),
('--place-self-start'),
('--place-self-end');

CREATE TABLE Grid
(
    id          TINYINT         UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    class       VARCHAR(20)     NOT NULL    UNIQUE,
    valor       VARCHAR(30)     NOT NULL,
    property    TINYINT         UNSIGNED    NOT NULL,
    source      TINYINT         UNSIGNED    NOT NULL,
    media       TINYINT         UNSIGNED    NOT NULL,
    concat      TINYINT(1)      NOT NULL,
    CONSTRAINT  grid_property   FOREIGN KEY (property)  REFERENCES  GridProperty(id)
)
    ENGINE=INNODB DEFAULT CHARSET=UTF8;


INSERT INTO Grid
(class,                 valor,  property,   source, media,  concat)
VALUES
('grid-2tn',            1,      1,          1,      1,      1),
('fluid-2tn',           1,      1,          1,      1,      1),
('grid-3tn',            2,      1,          1,      1,      1),
('fluid-3tn',           2,      1,          1,      1,      1),
('grid-4tn',            3,      1,          1,      1,      1),
('fluid-4tn',           3,      1,          1,      1,      1),
('grid-5tn',            4,      1,          1,      1,      1),
('fluid-5tn',           4,      1,          1,      1,      1),
('grid-6tn',            5,      1,          1,      1,      1),
('fluid-6tn',           5,      1,          1,      1,      1),
('grid-7tn',            6,      1,          1,      1,      1),
('fluid-7tn',           6,      1,          1,      1,      1),
('grid-8tn',            7,      1,          1,      1,      1),
('fluid-8tn',           7,      1,          1,      1,      1),
('grid-9tn',            8,      1,          1,      1,      1),
('fluid-9tn',           8,      1,          1,      1,      1),
('grid-10tn',           9,      1,          1,      1,      1),
('fluid-10tn',          9,      1,          1,      1,      1),
('grid-11tn',           10,     1,          1,      1,      1),
('fluid-11tn',          10,     1,          1,      1,      1),
('grid-12tn',           11,     1,          1,      1,      1),
('fluid-12tn',          11,     1,          1,      1,      1),
('grid-2sm',            1,      1,          1,      2,      1),
('fluid-2sm',           1,      1,          1,      2,      1),
('grid-3sm',            2,      1,          1,      2,      1),
('fluid-3sm',           2,      1,          1,      2,      1),
('grid-4sm',            3,      1,          1,      2,      1),
('fluid-4sm',           3,      1,          1,      2,      1),
('grid-5sm',            4,      1,          1,      2,      1),
('fluid-5sm',           4,      1,          1,      2,      1),
('grid-6sm',            5,      1,          1,      2,      1),
('fluid-6sm',           5,      1,          1,      2,      1),
('grid-7sm',            6,      1,          1,      2,      1),
('fluid-7sm',           6,      1,          1,      2,      1),
('grid-8sm',            7,      1,          1,      2,      1),
('fluid-8sm',           7,      1,          1,      2,      1),
('grid-9sm',            8,      1,          1,      2,      1),
('fluid-9sm',           8,      1,          1,      2,      1),
('grid-10sm',           9,      1,          1,      2,      1),
('fluid-10sm',          9,      1,          1,      2,      1),
('grid-11sm',           10,     1,          1,      2,      1),
('fluid-11sm',          10,     1,          1,      2,      1),
('grid-12sm',           11,     1,          1,      2,      1),
('fluid-12sm',          11,     1,          1,      2,      1),
('grid-2md',            1,      1,          1,      3,      1),
('fluid-2md',           1,      1,          1,      3,      1),
('grid-3md',            2,      1,          1,      3,      1),
('fluid-3md',           2,      1,          1,      3,      1),
('grid-4md',            3,      1,          1,      3,      1),
('fluid-4md',           3,      1,          1,      3,      1),
('grid-5md',            4,      1,          1,      3,      1),
('fluid-5md',           4,      1,          1,      3,      1),
('grid-6md',            5,      1,          1,      3,      1),
('fluid-6md',           5,      1,          1,      3,      1),
('grid-7md',            6,      1,          1,      3,      1),
('fluid-7md',           6,      1,          1,      3,      1),
('grid-8md',            7,      1,          1,      3,      1),
('fluid-8md',           7,      1,          1,      3,      1),
('grid-9md',            8,      1,          1,      3,      1),
('fluid-9md',           8,      1,          1,      3,      1),
('grid-10md',           9,      1,          1,      3,      1),
('fluid-10md',          9,      1,          1,      3,      1),
('grid-11md',           10,     1,          1,      3,      1),
('fluid-11md',          10,     1,          1,      3,      1),
('grid-12md',           11,     1,          1,      3,      1),
('fluid-12md',          11,     1,          1,      3,      1),
('grid-2lg',            1,      1,          1,      4,      1),
('fluid-2lg',           1,      1,          1,      4,      1),
('grid-3lg',            2,      1,          1,      4,      1),
('fluid-3lg',           2,      1,          1,      4,      1),
('grid-4lg',            3,      1,          1,      4,      1),
('fluid-4lg',           3,      1,          1,      4,      1),
('grid-5lg',            4,      1,          1,      4,      1),
('fluid-5lg',           4,      1,          1,      4,      1),
('grid-6lg',            5,      1,          1,      4,      1),
('fluid-6lg',           5,      1,          1,      4,      1),
('grid-7lg',            6,      1,          1,      4,      1),
('fluid-7lg',           6,      1,          1,      4,      1),
('grid-8lg',            7,      1,          1,      4,      1),
('fluid-8lg',           7,      1,          1,      4,      1),
('grid-9lg',            8,      1,          1,      4,      1),
('fluid-9lg',           8,      1,          1,      4,      1),
('grid-10lg',           9,      1,          1,      4,      1),
('fluid-10lg',          9,      1,          1,      4,      1),
('grid-11lg',           10,     1,          1,      4,      1),
('fluid-11lg',          10,     1,          1,      4,      1),
('grid-12lg',           11,     1,          1,      4,      1),
('fluid-12lg',          11,     1,          1,      4,      1),
('grid-2wd',            1,      1,          1,      5,      1),
('fluid-2wd',           1,      1,          1,      5,      1),
('grid-3wd',            2,      1,          1,      5,      1),
('fluid-3wd',           2,      1,          1,      5,      1),
('grid-4wd',            3,      1,          1,      5,      1),
('fluid-4wd',           3,      1,          1,      5,      1),
('grid-5wd',            4,      1,          1,      5,      1),
('fluid-5wd',           4,      1,          1,      5,      1),
('grid-6wd',            5,      1,          1,      5,      1),
('fluid-6wd',           5,      1,          1,      5,      1),
('grid-7wd',            6,      1,          1,      5,      1),
('fluid-7wd',           6,      1,          1,      5,      1),
('grid-8wd',            7,      1,          1,      5,      1),
('fluid-8wd',           7,      1,          1,      5,      1),
('grid-9wd',            8,      1,          1,      5,      1),
('fluid-9wd',           8,      1,          1,      5,      1),
('grid-10wd',           9,      1,          1,      5,      1),
('fluid-10wd',          9,      1,          1,      5,      1),
('grid-11wd',           10,     1,          1,      5,      1),
('fluid-11wd',          10,     1,          1,      5,      1),
('grid-12wd',           11,     1,          1,      5,      1),
('fluid-12wd',          11,     1,          1,      5,      1),
('gap-1tn',             12,     2,          1,      1,      1),
('gap-2tn',             13,     2,          1,      1,      1),
('gap-3tn',             14,     2,          1,      1,      1),
('gap-1sm',             15,     2,          1,      2,      1),
('gap-2sm',             16,     2,          1,      2,      1),
('gap-3sm',             17,     2,          1,      2,      1),
('gap-1md',             18,     2,          1,      3,      1),
('gap-2md',             19,     2,          1,      3,      1),
('gap-3md',             20,     2,          1,      3,      1),
('gap-1lg',             21,     2,          1,      4,      1),
('gap-2lg',             22,     2,          1,      4,      1),
('gap-3lg',             23,     2,          1,      4,      1),
('gap-1wd',             24,     2,          1,      5,      1),
('gap-2wd',             25,     2,          1,      5,      1),
('gap-3wd',             26,     2,          1,      5,      1),
('placo-around',        27,     3,          3,      1,      0),
('placo-between',       28,     3,          3,      1,      0),
('placo-evenly',        29,     3,          3,      1,      0),
('placo-center',        30,     3,          3,      1,      0),
('placo-stretch',       31,     3,          3,      1,      0),
('placo-start',         34,     3,          3,      1,      0),
('placo-end',           35,     3,          3,      1,      0),
('placo-around-sm',     27,     3,          3,      2,      0),
('placo-between-sm',    28,     3,          3,      2,      0),
('placo-evenly-sm',     29,     3,          3,      2,      0),
('placo-center-sm',     30,     3,          3,      2,      0),
('placo-stretch-sm',    31,     3,          3,      2,      0),
('placo-start-sm',      34,     3,          3,      2,      0),
('placo-end-sm',        35,     3,          3,      2,      0),
('placo-around-md',     27,     3,          3,      3,      0),
('placo-between-md',    28,     3,          3,      3,      0),
('placo-evenly-md',     29,     3,          3,      3,      0),
('placo-center-md',     30,     3,          3,      3,      0),
('placo-stretch-md',    31,     3,          3,      3,      0),
('placo-start-md',      34,     3,          3,      3,      0),
('placo-end-md',        35,     3,          3,      3,      0),
('placo-around-lg',     27,     3,          3,      4,      0),
('placo-between-lg',    28,     3,          3,      4,      0),
('placo-evenly-lg',     29,     3,          3,      4,      0),
('placo-center-lg',     30,     3,          3,      4,      0),
('placo-stretch-lg',    31,     3,          3,      4,      0),
('placo-start-lg',      34,     3,          3,      4,      0),
('placo-end-lg',        35,     3,          3,      4,      0),
('placo-around-wd',     27,     3,          3,      5,      0),
('placo-between-wd',    28,     3,          3,      5,      0),
('placo-evenly-wd',     29,     3,          3,      5,      0),
('placo-center-wd',     30,     3,          3,      5,      0),
('placo-stretch-wd',    31,     3,          3,      5,      0),
('placo-start-wd',      34,     3,          3,      5,      0),
('placo-end-wd',        35,     3,          3,      5,      0),
('plait-auto',          33,     4,          3,      1,      0),
('plait-base',          36,     4,          3,      1,      0),
('plait-normal',        32,     4,          3,      1,      0),
('plait-center',        30,     4,          3,      1,      0),
('plait-stretch',       31,     4,          3,      1,      0),
('plait-start',         37,     4,          3,      1,      0),
('plait-end',           38,     4,          3,      1,      0),
('plait-auto-sm',       33,     4,          3,      2,      0),
('plait-base-sm',       36,     4,          3,      2,      0),
('plait-normal-sm',     32,     4,          3,      2,      0),
('plait-center-sm',     30,     4,          3,      2,      0),
('plait-stretch-sm',    31,     4,          3,      2,      0),
('plait-start-sm',      37,     4,          3,      2,      0),
('plait-end-sm',        38,     4,          3,      2,      0),
('plait-auto-md',       33,     4,          3,      3,      0),
('plait-base-md',       36,     4,          3,      3,      0),
('plait-normal-md',     32,     4,          3,      3,      0),
('plait-center-md',     30,     4,          3,      3,      0),
('plait-stretch-md',    31,     4,          3,      3,      0),
('plait-start-md',      37,     4,          3,      3,      0),
('plait-end-md',        38,     4,          3,      3,      0),
('plait-auto-lg',       33,     4,          3,      4,      0),
('plait-base-lg',       36,     4,          3,      4,      0),
('plait-normal-lg',     32,     4,          3,      4,      0),
('plait-center-lg',     30,     4,          3,      4,      0),
('plait-stretch-lg',    31,     4,          3,      4,      0),
('plait-start-lg',      37,     4,          3,      4,      0),
('plait-end-lg',        38,     4,          3,      4,      0),
('plait-auto-wd',       33,     4,          3,      5,      0),
('plait-base-wd',       36,     4,          3,      5,      0),
('plait-normal-wd',     32,     4,          3,      5,      0),
('plait-center-wd',     30,     4,          3,      5,      0),
('plait-stretch-wd',    31,     4,          3,      5,      0),
('plait-start-wd',      37,     4,          3,      5,      0),
('plait-end-wd',        38,     4,          3,      5,      0),
('plase-auto',          33,     5,          3,      1,      0),
('plase-base',          39,     5,          3,      1,      0),
('plase-normal',        32,     5,          3,      1,      0),
('plase-center',        30,     5,          3,      1,      0),
('plase-stretch',       31,     5,          3,      1,      0),
('plase-start',         40,     5,          3,      1,      0),
('plase-end',           41,     5,          3,      1,      0),
('plase-auto-sm',       33,     5,          3,      2,      0),
('plase-base-sm',       39,     5,          3,      2,      0),
('plase-normal-sm',     32,     5,          3,      2,      0),
('plase-center-sm',     30,     5,          3,      2,      0),
('plase-stretch-sm',    31,     5,          3,      2,      0),
('plase-start-sm',      40,     5,          3,      2,      0),
('plase-end-sm',        41,     5,          3,      2,      0),
('plase-auto-md',       33,     5,          3,      3,      0),
('plase-base-md',       39,     5,          3,      3,      0),
('plase-normal-md',     32,     5,          3,      3,      0),
('plase-center-md',     30,     5,          3,      3,      0),
('plase-stretch-md',    31,     5,          3,      3,      0),
('plase-start-md',      40,     5,          3,      3,      0),
('plase-end-md',        41,     5,          3,      3,      0),
('plase-auto-lg',       33,     5,          3,      4,      0),
('plase-base-lg',       39,     5,          3,      4,      0),
('plase-normal-lg',     32,     5,          3,      4,      0),
('plase-center-lg',     30,     5,          3,      4,      0),
('plase-stretch-lg',    31,     5,          3,      4,      0),
('plase-start-lg',      40,     5,          3,      4,      0),
('plase-end-lg',        41,     5,          3,      4,      0),
('plase-auto-wd',       33,     3,          3,      5,      0),
('plase-base-wd',       39,     3,          3,      5,      0),
('plase-normal-wd',     32,     3,          3,      5,      0),
('plase-center-wd',     30,     3,          3,      5,      0),
('plase-stretch-wd',    31,     3,          3,      5,      0),
('plase-start-wd',      40,     3,          3,      5,      0),
('plase-end-wd',        41,     3,          3,      5,      0);