USE animadio;

INSERT INTO Part
(part)
VALUES
('box'),
('grid'),
('states'),
('helpers');

INSERT INTO Media
(media,     screen)
VALUES
('tn',      'All'),
('sm',      'min-width: 576px'),
('md',      'min-width: 768px'),
('lg',      'min-width: 992px'),
('wd',      'min-width: 1200px');

INSERT INTO Source
(source)
VALUES
('container'),
('mar'),
('bord'),
('pad'),
('height'),
('width'),
('flex'),
('grid'),
('place'),
('anima'),
('display'),
('position'),
('bg'),
('color'),
('font'),
('align'),
('deco'),
('shatex'),
('shabox'),
('cursor');

INSERT INTO Property
(property)
VALUES
('margin'),
('margin-top'),
('margin-right'),
('margin-bottom'),
('margin-left'),
('border-style'),
('border-width'),
('border-radius'),
('border-color'),
('padding'),
('padding-top'),
('padding-right'),
('padding-bottom'),
('padding-left'),
('height'),
('max-height'),
('min-height'),
('width'),
('max-width'),
('min-width'),
('grid-template'),
('grid-gap'),
('place-content'),
('place-items'),
('place-self'),
('animation-name'),
('animation-duration'),
('animation-timing-function'),
('animation-iteration-count'),
('animation-delay'),
('animation-direction'),
('animation-fill-mode'),
('display'),
('position'),
('background-color'),
('color'),
('font-weight'),
('font-style'),
('font-family'),
('text-align'),
('text-decoration-line'),
('text-decoration-style'),
('text-decoration-color'),
('text-shadow'),
('box-shadow'),
('cursor');

INSERT INTO Valor
(valor)
VALUES
('--black'),
('--blue'),
('--gray'),
('--green'),
('--maroon'),
('--navy'),
('--orange'),
('--purple'),
('--red'),
('--yellow'),
('--white'),
('--sky'),
('--silver'),
('--jade'),
('--choco'),
('--aqua'),
('--salmon'),
('--violet'),
('--tomato'),
('--khaki'),
('--fb'),
('--fcc'),
('--github'),
('--jsd'),
('--in'),
('--medium'),
('--npm'),
('--packagist'),
('--stack'),
('--tw'),
('--black-dark'),
('--blue-dark'),
('--gray-dark'),
('--green-dark'),
('--maroon-dark'),
('--navy-dark'),
('--orange-dark'),
('--purple-dark'),
('--red-dark'),
('--yellow-dark'),
('--white-dark'),
('--sky-dark'),
('--silver-dark'),
('--jade-dark'),
('--choco-dark'),
('--aqua-dark'),
('--salmon-dark'),
('--violet-dark'),
('--tomato-dark'),
('--khaki-dark'),
('--black-light'),
('--blue-light'),
('--gray-light'),
('--green-light'),
('--maroon-light'),
('--navy-light'),
('--orange-light'),
('--purple-light'),
('--red-light'),
('--yellow-light'),
('--sans-serif-font-family'),
('--serif-font-family'),
('--monospace-font-family'),
('--cursive-font-family'),
('--fantasy-font-family'),
('100%'),
('50%'),
('60%'),
('70%'),
('80%'),
('90%'),
('--margin-none'),
('--margin-sm'),
('--margin-md'),
('--margin-lg'),
('--margin-top-sm'),
('--margin-top-md'),
('--margin-top-lg'),
('--margin-right-sm'),
('--margin-right-md'),
('--margin-right-lg'),
('--margin-bottom-sm'),
('--margin-bottom-md'),
('--margin-bottom-lg'),
('--margin-left-sm'),
('--margin-left-md'),
('--margin-left-lg'),
('--border-style'),
('dashed'),
('dotted'),
('solid'),
('double'),
('groove'),
('ridge'),
('inset'),
('outset'),
('--border-width-tn'),
('--border-width-sm'),
('--border-width-md'),
('--border-width-lg'),
('--border-width-wd'),
('--border-radius-square'),
('--border-radius-curve'),
('--border-radius-rounded'),
('--border-radius-circle'),
('--padding-none'),
('--padding-sm'),
('--padding-md'),
('--padding-lg'),
('--padding-top-sm'),
('--padding-top-md'),
('--padding-top-lg'),
('--padding-right-sm'),
('--padding-right-md'),
('--padding-right-lg'),
('--padding-bottom-sm'),
('--padding-bottom-md'),
('--padding-bottom-lg'),
('--padding-left-sm'),
('--padding-left-md'),
('--padding-left-lg'),
('--height-sm'),
('--height-md'),
('--height-lg'),
('--max-height-sm'),
('--max-height-md'),
('--max-height-lg'),
('--min-height-sm'),
('--min-height-md'),
('--min-height-lg'),
('--width-sm'),
('--width-md'),
('--width-lg'),
('--max-width-sm'),
('--max-width-md'),
('--max-width-lg'),
('--min-width-sm'),
('--min-width-md'),
('--min-width-lg'),
('auto/repeat(2, auto)'),
('auto/repeat(3, auto)'),
('auto/repeat(4, auto)'),
('auto/repeat(5, auto)'),
('auto/repeat(6, auto)'),
('auto/repeat(7, auto)'),
('auto/repeat(8, auto)'),
('auto/repeat(9, auto)'),
('auto/repeat(10, auto)'),
('auto/repeat(11, auto)'),
('auto/repeat(12, auto)'),
('--gap-1tn'),
('--gap-2tn'),
('--gap-3tn'),
('--gap-1sm'),
('--gap-2sm'),
('--gap-3sm'),
('--gap-1md'),
('--gap-2md'),
('--gap-3md'),
('--gap-1lg'),
('--gap-2lg'),
('--gap-3lg'),
('--gap-1wd'),
('--gap-2wd'),
('--gap-3wd'),
('space-around'),
('space-between'),
('space-evenly'),
('center'),
('stretch'),
('normal'),
('auto'),
('--place-content-start'),
('--place-content-end'),
('--place-items-base'),
('--place-items-start'),
('--place-items-end'),
('--place-self-base'),
('--place-self-start'),
('--place-self-end'),
('--animation-duration'),
('--animation-duration-tn'),
('--animation-duration-sm'),
('--animation-duration-md'),
('--animation-duration-lg'),
('--animation-duration-wd'),
('--animation-timing-function-linear'),
('--animation-timing-function-in'),
('--animation-timing-function-out'),
('--animation-timing-function-inout'),
('--animation-timing-function-bezier'),
('--animation-timing-function-start'),
('--animation-timing-function-end'),
('--animation-timing-function-chrono'),
('--animation-timing-function-timer'),
('--animation-iteration-count-few'),
('--animation-iteration-count-many'),
('--animation-iteration-count-loop'),
('--animation-delay-small'),
('--animation-delay-medium'),
('--animation-delay-large'),
('alternate'),
('reverse'),
('alternate-reverse'),
('forwards'),
('backwards'),
('both'),
('none'),
('inline'),
('block'),
('inline-block'),
('absolute'),
('fixed'),
('relative'),
('sticky'),
('bold'),
('italic'),
('oblique'),
('justify'),
('right'),
('left'),
('--text-decoration-line'),
('underline'),
('overline'),
('line-through'),
('wavy'),
('--text-shadow-sm'),
('--text-shadow-md'),
('--text-shadow-lg'),
('--text-shadow-blur'),
('--text-shadow-blur-sm'),
('--text-shadow-blur-md'),
('--text-shadow-blur-lg'),
('--box-shadow-sm'),
('--box-shadow-md'),
('--box-shadow-lg'),
('--box-shadow-blur'),
('--box-shadow-blur-sm'),
('--box-shadow-blur-md'),
('--box-shadow-blur-lg'),
('--box-shadow-spread'),
('--box-shadow-spread-sm'),
('--box-shadow-spread-md'),
('--box-shadow-spread-lg'),
('cell'),
('crosshair'),
('pointer'),
('help'),
('move'),
('not-allowed'),
('text');

INSERT INTO Class
(class,                 part_id,  source_id,    property_id,  valor_id,     media_id, concat)
VALUES
('container-50tn',      1,        1,            19,           67,           1,        1),
('container-60tn',      1,        1,            19,           68,           1,        1),
('container-70tn',      1,        1,            19,           69,           1,        1),
('container-80tn',      1,        1,            19,           70,           1,        1),
('container-90tn',      1,        1,            19,           71,           1,        1),
('container-50sm',      1,        1,            19,           67,           2,        1),
('container-60sm',      1,        1,            19,           68,           2,        1),
('container-70sm',      1,        1,            19,           69,           2,        1),
('container-80sm',      1,        1,            19,           70,           2,        1),
('container-90sm',      1,        1,            19,           71,           2,        1),
('container-50md',      1,        1,            19,           67,           3,        1),
('container-60md',      1,        1,            19,           68,           3,        1),
('container-70md',      1,        1,            19,           69,           3,        1),
('container-80md',      1,        1,            19,           70,           3,        1),
('container-90md',      1,        1,            19,           71,           3,        1),
('container-50lg',      1,        1,            19,           67,           4,        1),
('container-60lg',      1,        1,            19,           68,           4,        1),
('container-70lg',      1,        1,            19,           69,           4,        1),
('container-80lg',      1,        1,            19,           70,           4,        1),
('container-90lg',      1,        1,            19,           71,           4,        1),
('container-50wd',      1,        1,            19,           67,           5,        1),
('container-60wd',      1,        1,            19,           68,           5,        1),
('container-70wd',      1,        1,            19,           69,           5,        1),
('container-80wd',      1,        1,            19,           70,           5,        1),
('container-90wd',      1,        1,            19,           71,           5,        1),
('mar-none',            1,        2,            1,            72,           1,        0),
('mar-top-none',        1,        2,            2,            72,           1,        0),
('mar-right-none',      1,        2,            3,            72,           1,        0),
('mar-bot-none',        1,        2,            4,            72,           1,        0),
('mar-left-none',       1,        2,            5,            72,           1,        0),
('mar-sm',              1,        2,            1,            73,           1,        0),
('mar-md',              1,        2,            1,            74,           1,        0),
('mar-lg',              1,        2,            1,            75,           1,        0),
('mar-top-sm',          1,        2,            2,            76,           1,        0),
('mar-top-md',          1,        2,            2,            77,           1,        0),
('mar-top-lg',          1,        2,            2,            78,           1,        0),
('mar-right-sm',        1,        2,            3,            79,           1,        0),
('mar-right-md',        1,        2,            3,            80,           1,        0),
('mar-right-lg',        1,        2,            3,            81,           1,        0),
('mar-bot-sm',          1,        2,            4,            82,           1,        0),
('mar-bot-md',          1,        2,            4,            83,           1,        0),
('mar-bot-lg',          1,        2,            4,            84,           1,        0),
('mar-left-sm',         1,        2,            5,            85,           1,        0),
('mar-left-md',         1,        2,            5,            86,           1,        0),
('mar-left-lg',         1,        2,            5,            87,           1,        0),
('bord',                1,        3,            6,            88,           1,        0),
('bord-dash',           1,        3,            6,            89,           1,        0),
('bord-dot',            1,        3,            6,            90,           1,        0),
('bord-solid',          1,        3,            6,            91,           1,        0),
('bord-double',         1,        3,            6,            92,           1,        0),
('bord-groove',         1,        3,            6,            93,           1,        0),
('bord-ridge',          1,        3,            6,            94,           1,        0),
('bord-in',             1,        3,            6,            95,           1,        0),
('bord-out',            1,        3,            6,            96,           1,        0),
('bord-tn',             1,        3,            7,            97,           1,        0),
('bord-sm',             1,        3,            7,            98,           1,        0),
('bord-md',             1,        3,            7,            99,           1,        0),
('bord-lg',             1,        3,            7,            100,          1,        0),
('bord-wd',             1,        3,            7,            101,          1,        0),
('bord-square',         1,        3,            8,            102,          1,        0),
('bord-curve',          1,        3,            8,            103,          1,        0),
('bord-rounded',        1,        3,            8,            104,          1,        0),
('bord-circle',         1,        3,            8,            105,          1,        0),
('bord-black',          1,        3,            9,            1,            1,        0),
('bord-blue',           1,        3,            9,            2,            1,        0),
('bord-gray',           1,        3,            9,            3,            1,        0),
('bord-green',          1,        3,            9,            4,            1,        0),
('bord-maroon',         1,        3,            9,            5,            1,        0),
('bord-navy',           1,        3,            9,            6,            1,        0),
('bord-orange',         1,        3,            9,            7,            1,        0),
('bord-purple',         1,        3,            9,            8,            1,        0),
('bord-red',            1,        3,            9,            9,            1,        0),
('bord-yellow',         1,        3,            9,            10,           1,        0),
('bord-white',          1,        3,            9,            11,           1,        0),
('bord-sky',            1,        3,            9,            12,           1,        0),
('bord-silver',         1,        3,            9,            13,           1,        0),
('bord-jade',           1,        3,            9,            14,           1,        0),
('bord-choco',          1,        3,            9,            15,           1,        0),
('bord-aqua',           1,        3,            9,            16,           1,        0),
('bord-salmon',         1,        3,            9,            17,           1,        0),
('bord-violet',         1,        3,            9,            18,           1,        0),
('bord-tomato',         1,        3,            9,            19,           1,        0),
('bord-khaki',          1,        3,            9,            20,           1,        0),
('pad-none',            1,        4,            10,           106,          1,        0),
('pad-top-none',        1,        4,            11,           106,          1,        0),
('pad-right-none',      1,        4,            12,           106,          1,        0),
('pad-bot-none',        1,        4,            13,           106,          1,        0),
('pad-left-none',       1,        4,            14,           106,          1,        0),
('pad-sm',              1,        4,            10,           107,          1,        0),
('pad-md',              1,        4,            10,           108,          1,        0),
('pad-lg',              1,        4,            10,           109,          1,        0),
('pad-top-sm',          1,        4,            11,           110,          1,        0),
('pad-top-md',          1,        4,            11,           111,          1,        0),
('pad-top-lg',          1,        4,            11,           112,          1,        0),
('pad-right-sm',        1,        4,            12,           113,          1,        0),
('pad-right-md',        1,        4,            12,           114,          1,        0),
('pad-right-lg',        1,        4,            12,           115,          1,        0),
('pad-bot-sm',          1,        4,            13,           116,          1,        0),
('pad-bot-md',          1,        4,            13,           117,          1,        0),
('pad-bot-lg',          1,        4,            13,           118,          1,        0),
('pad-left-sm',         1,        4,            14,           119,          1,        0),
('pad-left-md',         1,        4,            14,           120,          1,        0),
('pad-left-lg',         1,        4,            14,           121,          1,        0),
('height-sm',           1,        5,            15,           122,          1,        0),
('height-md',           1,        5,            15,           123,          1,        0),
('height-lg',           1,        5,            15,           124,          1,        0),
('max-h-sm',            1,        5,            16,           125,          1,        0),
('max-h-md',            1,        5,            16,           126,          1,        0),
('max-h-lg',            1,        5,            16,           127,          1,        0),
('min-h-sm',            1,        5,            17,           128,          1,        0),
('min-h-md',            1,        5,            17,           129,          1,        0),
('min-h-lg',            1,        5,            17,           130,          1,        0),
('width-sm',            1,        6,            18,           131,          1,        0),
('width-md',            1,        6,            18,           132,          1,        0),
('width-lg',            1,        6,            18,           133,          1,        0),
('max-w-sm',            1,        6,            19,           134,          1,        0),
('max-w-md',            1,        6,            19,           135,          1,        0),
('max-w-lg',            1,        6,            19,           136,          1,        0),
('min-w-sm',            1,        6,            20,           137,          1,        0),
('min-w-md',            1,        6,            20,           138,          1,        0),
('min-w-lg',            1,        6,            20,           139,          1,        0),
('grid-2tn',            2,        8,            21,           140,          1,        1),
('fluid-2tn',           2,        8,            21,           140,          1,        1),
('grid-3tn',            2,        8,            21,           141,          1,        1),
('fluid-3tn',           2,        8,            21,           141,          1,        1),
('grid-4tn',            2,        8,            21,           142,          1,        1),
('fluid-4tn',           2,        8,            21,           142,          1,        1),
('grid-5tn',            2,        8,            21,           143,          1,        1),
('fluid-5tn',           2,        8,            21,           143,          1,        1),
('grid-6tn',            2,        8,            21,           144,          1,        1),
('fluid-6tn',           2,        8,            21,           144,          1,        1),
('grid-7tn',            2,        8,            21,           145,          1,        1),
('fluid-7tn',           2,        8,            21,           145,          1,        1),
('grid-8tn',            2,        8,            21,           146,          1,        1),
('fluid-8tn',           2,        8,            21,           146,          1,        1),
('grid-9tn',            2,        8,            21,           147,          1,        1),
('fluid-9tn',           2,        8,            21,           147,          1,        1),
('grid-10tn',           2,        8,            21,           148,          1,        1),
('fluid-10tn',          2,        8,            21,           148,          1,        1),
('grid-11tn',           2,        8,            21,           149,          1,        1),
('fluid-11tn',          2,        8,            21,           149,          1,        1),
('grid-12tn',           2,        8,            21,           150,          1,        1),
('fluid-12tn',          2,        8,            21,           150,          1,        1),
('grid-2sm',            2,        8,            21,           140,          2,        1),
('fluid-2sm',           2,        8,            21,           140,          2,        1),
('grid-3sm',            2,        8,            21,           141,          2,        1),
('fluid-3sm',           2,        8,            21,           141,          2,        1),
('grid-4sm',            2,        8,            21,           142,          2,        1),
('fluid-4sm',           2,        8,            21,           142,          2,        1),
('grid-5sm',            2,        8,            21,           143,          2,        1),
('fluid-5sm',           2,        8,            21,           143,          2,        1),
('grid-6sm',            2,        8,            21,           144,          2,        1),
('fluid-6sm',           2,        8,            21,           144,          2,        1),
('grid-7sm',            2,        8,            21,           145,          2,        1),
('fluid-7sm',           2,        8,            21,           145,          2,        1),
('grid-8sm',            2,        8,            21,           146,          2,        1),
('fluid-8sm',           2,        8,            21,           146,          2,        1),
('grid-9sm',            2,        8,            21,           147,          2,        1),
('fluid-9sm',           2,        8,            21,           147,          2,        1),
('grid-10sm',           2,        8,            21,           148,          2,        1),
('fluid-10sm',          2,        8,            21,           148,          2,        1),
('grid-11sm',           2,        8,            21,           149,          2,        1),
('fluid-11sm',          2,        8,            21,           149,          2,        1),
('grid-12sm',           2,        8,            21,           150,          2,        1),
('fluid-12sm',          2,        8,            21,           150,          2,        1),
('grid-2md',            2,        8,            21,           140,          3,        1),
('fluid-2md',           2,        8,            21,           140,          3,        1),
('grid-3md',            2,        8,            21,           141,          3,        1),
('fluid-3md',           2,        8,            21,           141,          3,        1),
('grid-4md',            2,        8,            21,           142,          3,        1),
('fluid-4md',           2,        8,            21,           142,          3,        1),
('grid-5md',            2,        8,            21,           143,          3,        1),
('fluid-5md',           2,        8,            21,           143,          3,        1),
('grid-6md',            2,        8,            21,           144,          3,        1),
('fluid-6md',           2,        8,            21,           144,          3,        1),
('grid-7md',            2,        8,            21,           145,          3,        1),
('fluid-7md',           2,        8,            21,           145,          3,        1),
('grid-8md',            2,        8,            21,           146,          3,        1),
('fluid-8md',           2,        8,            21,           146,          3,        1),
('grid-9md',            2,        8,            21,           147,          3,        1),
('fluid-9md',           2,        8,            21,           147,          3,        1),
('grid-10md',           2,        8,            21,           148,          3,        1),
('fluid-10md',          2,        8,            21,           148,          3,        1),
('grid-11md',           2,        8,            21,           149,          3,        1),
('fluid-11md',          2,        8,            21,           149,          3,        1),
('grid-12md',           2,        8,            21,           150,          3,        1),
('fluid-12md',          2,        8,            21,           150,          3,        1),
('grid-2lg',            2,        8,            21,           140,          4,        1),
('fluid-2lg',           2,        8,            21,           140,          4,        1),
('grid-3lg',            2,        8,            21,           141,          4,        1),
('fluid-3lg',           2,        8,            21,           141,          4,        1),
('grid-4lg',            2,        8,            21,           142,          4,        1),
('fluid-4lg',           2,        8,            21,           142,          4,        1),
('grid-5lg',            2,        8,            21,           143,          4,        1),
('fluid-5lg',           2,        8,            21,           143,          4,        1),
('grid-6lg',            2,        8,            21,           144,          4,        1),
('fluid-6lg',           2,        8,            21,           144,          4,        1),
('grid-7lg',            2,        8,            21,           145,          4,        1),
('fluid-7lg',           2,        8,            21,           145,          4,        1),
('grid-8lg',            2,        8,            21,           146,          4,        1),
('fluid-8lg',           2,        8,            21,           146,          4,        1),
('grid-9lg',            2,        8,            21,           147,          4,        1),
('fluid-9lg',           2,        8,            21,           147,          4,        1),
('grid-10lg',           2,        8,            21,           148,          4,        1),
('fluid-10lg',          2,        8,            21,           148,          4,        1),
('grid-11lg',           2,        8,            21,           149,          4,        1),
('fluid-11lg',          2,        8,            21,           149,          4,        1),
('grid-12lg',           2,        8,            21,           150,          4,        1),
('fluid-12lg',          2,        8,            21,           150,          4,        1),
('grid-2wd',            2,        8,            21,           140,          5,        1),
('fluid-2wd',           2,        8,            21,           140,          5,        1),
('grid-3wd',            2,        8,            21,           141,          5,        1),
('fluid-3wd',           2,        8,            21,           141,          5,        1),
('grid-4wd',            2,        8,            21,           142,          5,        1),
('fluid-4wd',           2,        8,            21,           142,          5,        1),
('grid-5wd',            2,        8,            21,           143,          5,        1),
('fluid-5wd',           2,        8,            21,           143,          5,        1),
('grid-6wd',            2,        8,            21,           144,          5,        1),
('fluid-6wd',           2,        8,            21,           144,          5,        1),
('grid-7wd',            2,        8,            21,           145,          5,        1),
('fluid-7wd',           2,        8,            21,           145,          5,        1),
('grid-8wd',            2,        8,            21,           146,          5,        1),
('fluid-8wd',           2,        8,            21,           146,          5,        1),
('grid-9wd',            2,        8,            21,           147,          5,        1),
('fluid-9wd',           2,        8,            21,           147,          5,        1),
('grid-10wd',           2,        8,            21,           148,          5,        1),
('fluid-10wd',          2,        8,            21,           148,          5,        1),
('grid-11wd',           2,        8,            21,           149,          5,        1),
('fluid-11wd',          2,        8,            21,           149,          5,        1),
('grid-12wd',           2,        8,            21,           150,          5,        1),
('fluid-12wd',          2,        8,            21,           150,          5,        1),
('gap-1tn',             2,        8,            22,           151,          1,        1),
('gap-2tn',             2,        8,            22,           152,          1,        1),
('gap-3tn',             2,        8,            22,           153,          1,        1),
('gap-1sm',             2,        8,            22,           154,          2,        1),
('gap-2sm',             2,        8,            22,           155,          2,        1),
('gap-3sm',             2,        8,            22,           156,          2,        1),
('gap-1md',             2,        8,            22,           157,          3,        1),
('gap-2md',             2,        8,            22,           158,          3,        1),
('gap-3md',             2,        8,            22,           159,          3,        1),
('gap-1lg',             2,        8,            22,           160,          4,        1),
('gap-2lg',             2,        8,            22,           161,          4,        1),
('gap-3lg',             2,        8,            22,           162,          4,        1),
('gap-1wd',             2,        8,            22,           163,          5,        1),
('gap-2wd',             2,        8,            22,           164,          5,        1),
('gap-3wd',             2,        8,            22,           165,          5,        1);
