USE animadio;

INSERT INTO Part
(part)
VALUES
('global'),
('box'),
('grid'),
('elements'),
('states'),
('helpers');

INSERT INTO Source
(source)
VALUES
('variables'),
('keyframes'),
('init'),
('container'),
('margin'),
('border'),
('padding'),
('height'),
('width'),
('grid'),
('flex'),
('place'),
('btn'),
('card'),
('foot'),
('form'),
('gallery'),
('menu'),
('navbar'),
('table'),
('anima'),
('display'),
('position'),
('bg'),
('color'),
('font'),
('align'),
('deco'),
('shatex'),
('shabox'),
('cursor');

INSERT INTO Property
(property)
VALUES
('Multiple Properties'),
('animation'),
('animation-delay'),
('animation-direction'),
('animation-duration'),
('animation-fill-mode'),
('animation-iteration-count'),
('animation-name'),
('animation-timing-function'),
('background-color'),
('border'),
('border-collapse'),
('border-color'),
('border-radius'),
('border-spacing'),
('border-style'),
('border-width'),
('bottom'),
('box-shadow'),
('box-sizing'),
('caption-side'),
('color'),
('content'),
('cursor'),
('display'),
('flex-direction'),
('flex-wrap'),
('font-family'),
('font-size'),
('font-style'),
('font-weight'),
('grid-gap'),
('grid-template'),
('height'),
('left'),
('line-height'),
('list-style'),
('margin'),
('margin-bottom'),
('margin-left'),
('margin-right'),
('margin-top'),
('max-height'),
('max-width'),
('min-height'),
('min-width'),
('object-fit'),
('opacity'),
('outline'),
('overflow'),
('padding'),
('padding-bottom'),
('padding-left'),
('padding-right'),
('padding-top'),
('place-content'),
('place-items'),
('place-self'),
('position'),
('right'),
('scroll-behavior'),
('text-align'),
('text-decoration'),
('text-decoration-color'),
('text-decoration-line'),
('text-decoration-style'),
('text-shadow'),
('text-transform'),
('top'),
('transform'),
('transform-origin'),
('transition'),
('vertical-align'),
('width'),
('z-index');

INSERT INTO Valor
(valor)
VALUES
('Multiple Variables'),
('Multiple Values'),
('--amethyst'),
('--animation-delay'),
('--animation-delay-large'),
('--animation-delay-medium'),
('--animation-delay-small'),
('--animation-direction'),
('--animation-duration'),
('--animation-duration-xs'),
('--animation-duration-sm'),
('--animation-duration-md'),
('--animation-duration-lg'),
('--animation-duration-xl'),
('--animation-fill-mode'),
('--animation-iteration-count'),
('--animation-iteration-count-few'),
('--animation-iteration-count-many'),
('--animation-name'),
('--animation-timing-function'),
('--animation-timing-function-bezier'),
('--animation-timing-function-ease'),
('--animation-timing-function-steps'),
('--article-margin-bottom'),
('--black'),
('--blue'),
('--body-background-color'),
('--body-font-family'),
('--body-font-size'),
('--body-line-height'),
('--body-scroll-behavior'),
('--border-color'),
('--border-radius'),
('--border-radius-circle'),
('--border-radius-round'),
('--border-radius-square'),
('--border-style'),
('--border-width'),
('--border-width-lg'),
('--border-width-md'),
('--border-width-sm'),
('--box-shadow-blur-all'),
('--box-shadow-blur-lg'),
('--box-shadow-blur-md'),
('--box-shadow-blur-sm'),
('--box-shadow-lg'),
('--box-shadow-md'),
('--box-shadow-sm'),
('--box-shadow-spread-all'),
('--box-shadow-spread-lg'),
('--box-shadow-spread-md'),
('--box-shadow-spread-sm'),
('--btn-background-color'),
('--btn-black-border-color'),
('--btn-black-color'),
('--btn-blue-border-color'),
('--btn-blue-color'),
('--btn-border'),
('--btn-border-radius'),
('--btn-checked-transform'),
('--btn-choco-color'),
('--btn-choco-border-color'),
('--btn-circle-border-radius'),
('--btn-circle-sizes'),
('--btn-color'),
('--btn-font-size'),
('--btn-gray-border-color'),
('--btn-gray-color'),
('--btn-green-border-color'),
('--btn-green-color'),
('--btn-hover-animation'),
('--btn-hover-background-color'),
('--btn-hover-border'),
('--btn-hover-border-radius'),
('--btn-hover-color'),
('--btn-hover-box-shadow'),
('--btn-hover-transition'),
('--btn-jade-color'),
('--btn-jade-border-color'),
('--btn-khaki-color'),
('--btn-khaki-border-color'),
('--keyframes-rotate3d'),
('--btn-lg-font-size'),
('--btn-lg-padding'),
('--btn-margin'),
('--btn-maroon-border-color'),
('--btn-maroon-color'),
('--keyframes-rotateZ'),
('--keyframes-scale3d'),
('--btn-orange-border-color'),
('--btn-orange-color'),
('--btn-padding'),
('--btn-purple-color'),
('--btn-purple-border-color'),
('--btn-red-color'),
('--btn-red-border-color'),
('--btn-round-border-radius'),
('--btn-round-sizes'),
('--btn-salmon-color'),
('--btn-salmon-border-color'),
('--btn-silver-color'),
('--btn-silver-border-color'),
('--btn-sky-color'),
('--btn-sky-border-color'),
('--keyframes-scaleZ'),
('--btn-sm-font-size'),
('--btn-sm-padding'),
('--btn-square-border-radius'),
('--btn-square-sizes'),
('--btn-text-align'),
('--btn-tomato-color'),
('--btn-tomato-border-color'),
('--btn-violet-color'),
('--btn-violet-border-color'),
('--btn-white-color'),
('--btn-white-border-color'),
('--btn-yellow-color'),
('--btn-yellow-border-color'),
('--keyframes-translate3d'),
('--btn-xl-font-size'),
('--btn-xl-padding'),
('--keyframes-translateZ'),
('--btn-xs-font-size'),
('--btn-xs-padding'),
('--card-background-color'),
('--card-btn-color'),
('--card-btn-hover-background-color'),
('--card-btn-hover-color'),
('--card-blue-background-color'),
('--card-blue-title-box-shadow'),
('--card-blue-title-text-shadow'),
('--card-border'),
('--card-border-radius'),
('--card-box-shadow'),
('--card-btn-text-align'),
('--card-btn-width'),
('--card-child-background-color'),
('--card-child-border'),
('--card-child-border-radius'),
('--card-child-font-size'),
('--card-child-margin'),
('--card-child-max-width'),
('--card-child-padding'),
('--card-child-text-align'),
('--card-color'),
('--card-flex-direction'),
('--card-green-background-color'),
('--card-green-title-box-shadow'),
('--card-green-title-text-shadow'),
('--card-hover-transform'),
('--card-hover-transition'),
('--card-margin'),
('--card-overflow'),
('--card-padding'),
('--card-place-items'),
('--card-position'),
('--card-purple-background-color'),
('--card-purple-title-box-shadow'),
('--card-purple-title-text-shadow'),
('--card-red-background-color'),
('--card-red-title-box-shadow'),
('--card-red-title-text-shadow'),
('--card-selection-background-color'),
('--card-selection-color'),
('--card-title-box-shadow'),
('--card-title-font-size'),
('--card-title-text-shadow'),
('--card-yellow-background-color'),
('--card-yellow-title-box-shadow'),
('--card-yellow-title-text-shadow'),
('--card-width'),
('--choco'),
('--citrine'),
('--code-font-family'),
('--code-overflow'),
('--code-padding'),
('--code-background-color'),
('--code-color'),
('--column-padding'),
('--emerald'),
('--facebook'),
('--flex-negative-margin-lg'),
('--flex-negative-margin-md'),
('--flex-negative-margin-sm'),
('--flex-negative-margin-xl'),
('--flex-negative-margin-xs'),
('--flex-positive-margin-lg'),
('--flex-positive-margin-md'),
('--flex-positive-margin-sm'),
('--flex-positive-margin-xl'),
('--flex-positive-margin-xs'),
('--flex-width-lg'),
('--flex-width-md'),
('--flex-width-sm'),
('--flex-width-xl'),
('--flex-width-xs'),
('--foot-first-child-background-color'),
('--foot-first-child-cursor'),
('--foot-first-child-flex-direction'),
('--foot-first-child-font-color'),
('--foot-first-child-link-font-color'),
('--foot-first-child-link-hover-font-color'),
('--foot-first-child-link-margin-bottom'),
('--foot-first-child-list-cursor'),
('--foot-first-child-list-text-align'),
('--foot-first-child-margin'),
('--foot-first-child-place-content'),
('--foot-last-child-background-color'),
('--foot-last-child-cursor'),
('--foot-last-child-link-margin-left'),
('--foot-last-child-link-margin-right'),
('--foot-last-child-margin'),
('--foot-last-child-padding-top'),
('--foot-last-child-place-content'),
('--foot-list-padding-bottom'),
('--foot-text-align'),
('--foot-title-color'),
('--foot-title-font-size'),
('--form-action-border'),
('--form-action-box-shadow'),
('--form-action-cursor'),
('--form-action-hover-box-shadow'),
('--form-action-hover-transform'),
('--form-action-hover-transition'),
('--form-action-line-height'),
('--form-action-margin'),
('--form-action-width'),
('--form-border'),
('--form-box-shadow'),
('--form-field-background-color'),
('--form-field-border'),
('--form-field-border-radius'),
('--form-field-box-shadow'),
('--form-field-hover-border'),
('--form-field-hover-box-shadow'),
('--form-field-line-height'),
('--form-field-margin'),
('--form-field-outline'),
('--form-field-padding'),
('--form-field-placeholder-color'),
('--form-field-placeholder-font-style'),
('--form-field-width'),
('--form-fieldset-border'),
('--form-fieldset-margin-left'),
('--form-label-border'),
('--form-label-color'),
('--form-label-hover-border'),
('--form-label-margin'),
('--form-label-padding'),
('--form-label-text-decoration'),
('--form-legend-font-size'),
('--form-legend-font-weight'),
('--form-legend-margin'),
('--form-list-flex-direction'),
('--form-list-place-content'),
('--form-list-place-items'),
('--form-margin'),
('--form-padding'),
('--form-reset-background-color'),
('--form-reset-border'),
('--form-reset-color'),
('--form-reset-hover-background-color'),
('--form-reset-hover-color'),
('--form-submit-background-color'),
('--form-submit-border'),
('--form-submit-color'),
('--form-submit-hover-background-color'),
('--form-submit-hover-color'),
('--form-width'),
('--gallery-all-cursor'),
('--gallery-flex-wrap'),
('--gallery-figcaption-background-color'),
('--gallery-figcaption-bottom'),
('--gallery-figcaption-fa-background-color'),
('--gallery-figcaption-fa-border'),
('--gallery-figcaption-fa-padding'),
('--gallery-figcaption-fa-position'),
('--gallery-figcaption-fa-radius'),
('--gallery-figcaption-fa-right'),
('--gallery-figcaption-fa-top'),
('--gallery-figcaption-line-height'),
('--gallery-figcaption-position'),
('--gallery-figcaption-width'),
('--gallery-figure-border'),
('--gallery-figure-box-shadow'),
('--gallery-figure-hover-figcaption-animation'),
('--gallery-figure-hover-figcaption-bottom'),
('--gallery-figure-line-height'),
('--gallery-figure-margin'),
('--gallery-figure-overflow'),
('--gallery-place-content'),
('--gallery-place-items'),
('--gallery-figure-position'),
('--gallery-figure-width'),
('--gallery-link-all-cursor'),
('--gallery-link-all-margin'),
('--gallery-figcaption-padding'),
('--gallery-link-all-font-size'),
('--gallery-link-all-padding'),
('free-gallery-1'),
('--gallery-link-color'),
('--gallery-margin'),
('--gallery-max-width'),
('--gallery-overflow'),
('--gap-small-lg'),
('--gap-medium-lg'),
('--gap-large-lg'),
('--gap-small-md'),
('--gap-medium-md'),
('--gap-large-md'),
('--gap-small-sm'),
('--gap-medium-sm'),
('--gap-large-sm'),
('--gap-small-xl'),
('--gap-medium-xl'),
('--gap-large-xl'),
('--gap-small-xs'),
('--gap-medium-xs'),
('--gap-large-xs'),
('--github'),
('--gray'),
('--green'),
('--height-lg'),
('--height-md'),
('--height-sm'),
('--img-max-height'),
('--img-max-width'),
('--img-object-fit'),
('--jade'),
('--jsdelivr'),
('--keyframes-content1'),
('--keyframes-content2'),
('--keyframes-content3'),
('--keyframes-content4'),
('--keyframes-content5'),
('--keyframes-rotate'),
('--keyframes-rotateX'),
('--keyframes-rotateY'),
('--keyframes-scale'),
('--keyframes-scaleX'),
('--keyframes-scaleY'),
('--keyframes-skew'),
('--keyframes-skewX'),
('--keyframes-skewY'),
('--keyframes-translate'),
('--keyframes-translateX'),
('--keyframes-translateY'),
('--keyframes-translateY-opac'),
('--keyframes-translateY-xs'),
('--keyframes-width'),
('--khaki'),
('--label-cursor'),
('--linkedin'),
('--link-text-decoration'),
('--link-outline'),
('--list-margin'),
('--list-padding'),
('--list-style'),
('--margin-bottom-lg'),
('--margin-bottom-md'),
('--margin-bottom-sm'),
('--margin-left-lg'),
('--margin-left-md'),
('--margin-left-sm'),
('--margin-lg'),
('--margin-md'),
('--margin-none'),
('--margin-right-lg'),
('--margin-right-md'),
('--margin-right-sm'),
('--margin-sm'),
('--margin-top-lg'),
('--margin-top-md'),
('--margin-top-sm'),
('--maroon'),
('--max-height-lg'),
('--max-height-md'),
('--max-height-sm'),
('--max-width-lg'),
('--max-width-md'),
('--max-width-sm'),
('--menu-all-cursor'),
('--menu-background-color'),
('--menu-border'),
('--menu-border-radius'),
('--menu-checked-label-background-color'),
('--menu-checked-label-color'),
('--menu-checked-label-font-weight'),
('--menu-color'),
('--menu-fa-bottom'),
('--menu-fa-color'),
('--menu-fa-position'),
('--menu-flex-direction'),
('--menu-label-border-radius'),
('--menu-label-hover-background-color'),
('--menu-label-hover-border'),
('--menu-label-hover-color'),
('--menu-label-hover-font-style'),
('--menu-label-padding'),
('--menu-label-place-content'),
('--menu-label-place-items'),
('--menu-label-position'),
('--menu-label-width'),
('--menu-list-style'),
('--menu-margin'),
('--menu-padding'),
('--menu-place-content'),
('--menu-place-items'),
('--menu-width'),
('--min-height-lg'),
('--min-height-md'),
('--min-height-sm'),
('--min-width-lg'),
('--min-width-md'),
('--min-width-sm'),
('--navbar-background-color'),
('--navbar-bottom'),
('--navbar-brand-link-img-height'),
('--navbar-brand-link-left'),
('--navbar-color'),
('--navbar-first-list-link-hover-scale'),
('--navbar-flex-direction'),
('--navbar-height'),
('--navbar-icon-place-self'),
('--navbar-left'),
('--navbar-label-animation'),
('--navbar-label-right'),
('--navbar-label-top'),
('--navbar-last-list-height'),
('--navbar-last-list-img-margin'),
('--navbar-last-list-link-hover-scale'),
('--navbar-link-color'),
('--navbar-link-cursor'),
('--navbar-link-hover-color'),
('--navbar-link-padding'),
('--navbar-list-link-flex-direction'),
('--navbar-list-list-style'),
('--navbar-list-margin'),
('--navbar-list-padding'),
('--navbar-list-place-items'),
('--navbar-padding'),
('--navbar-place-content'),
('--navbar-place-items'),
('--navbar-position'),
('--navbar-right'),
('--navbar-top'),
('--navbar-z-index'),
('--npm'),
('--obsidian'),
('--orange'),
('--padding-bottom-lg'),
('--padding-bottom-md'),
('--padding-bottom-sm'),
('--padding-left-lg'),
('--padding-left-md'),
('--padding-left-sm'),
('--padding-lg'),
('--padding-md'),
('--padding-none'),
('--padding-right-lg'),
('--padding-right-md'),
('--padding-right-sm'),
('--padding-sm'),
('--padding-top-lg'),
('--padding-top-md'),
('--padding-top-sm'),
('--place-content-end'),
('--place-content-start'),
('--place-items-baseline'),
('--place-items-end'),
('--place-items-start'),
('--place-self-baseline'),
('--place-self-end'),
('--place-self-start'),
('--purple'),
('--quartz'),
('--red'),
('--row-padding'),
('--ruby'),
('--salmon'),
('--sapphire'),
('--silver'),
('--sky'),
('--slider-check-direction-animation-direction'),
('--slider-check-direction-list-icon-before-content'),
('--slider-check-play-animation'),
('--slider-check-play-list-icon-before-color'),
('--slider-check-play-list-icon-before-content'),
('--slider-check-repeat-animation-iteration-count'),
('--slider-check-repeat-list-icon-before-content'),
('--slider-figure-margin'),
('--slider-figure-max-height'),
('--slider-figure-max-width'),
('--slider-figure-object-fit'),
('--slider-hover-list-opacity'),
('--slider-icon-color'),
('--slider-list-background-color'),
('--slider-list-border'),
('--slider-list-border-radius'),
('--slider-list-label-color'),
('--slider-list-label-padding'),
('--slider-list-link-color'),
('--slider-list-margin'),
('--slider-list-opacity'),
('--slider-list-padding'),
('--slider-list-place-content'),
('--slider-list-width'),
('--slider-margin'),
('--slider-min-height'),
('--slider-position'),
('--slider-progress-background-color'),
('--slider-progress-height'),
('--slider-radio-list-icon-before-content'),
('--slider-radio1-checked-progress-width'),
('--slider-radio2-checked-progress-width'),
('--slider-radio3-checked-progress-width'),
('--slider-radio4-checked-progress-width'),
('--slider-radio5-checked-progress-width'),
('--slider-text-align'),
('--slider-transition-color'),
('--slider-transition-opacity'),
('--slider-width'),
('--stack-overflow'),
('--card-btn-font-weight'),
('--table-border-spacing'),
('--table-box-shadow'),
('--table-caption-color'),
('--table-caption-font-size'),
('--table-caption-font-weight'),
('--table-caption-margin-bottom'),
('--table-caption-side'),
('--table-caption-text-shadow'),
('--table-cell-border-color'),
('--table-cell-border-radius'),
('--table-cell-border-style'),
('--table-cell-border-width'),
('--table-cell-cursor'),
('--table-cell-padding'),
('--table-cell-text-align'),
('--table-cell-vertical-align'),
('--table-font-family'),
('--table-margin'),
('--table-margin-bottom'),
('--table-text-align'),
('--table-vertical-align'),
('--table-width'),
('--table-row-even-background-color'),
('--table-row-even-color'),
('--table-row-even-hover-background-color'),
('--table-row-even-hover-box-shadow'),
('--table-row-even-hover-color'),
('--table-row-even-selection-background-color'),
('--table-row-even-selection-color'),
('--table-row-hover-box-shadow'),
('--table-row-odd-background-color'),
('--table-row-odd-color'),
('--table-row-odd-hover-background-color'),
('--table-row-odd-hover-box-shadow'),
('--table-row-odd-hover-color'),
('--table-row-odd-selection-background-color'),
('--table-row-odd-selection-color'),
('--table-title-background-color'),
('--table-title-color'),
('--table-title-font-style'),
('--table-title-selection-background-color'),
('--table-title-selection-color'),
('--text-decoration-color'),
('--text-decoration-line'),
('--text-decoration-style'),
('--text-shadow-blur-all'),
('--text-shadow-blur-lg'),
('--text-shadow-blur-md'),
('--text-shadow-blur-sm'),
('--text-shadow-lg'),
('--text-shadow-md'),
('--text-shadow-sm'),
('--title-font-family'),
('--title-lg-font-size'),
('--title-lg-text-transform'),
('--title-md-font-size'),
('--title-sm-font-size'),
('--title-xl-font-size'),
('--title-xl-text-transform'),
('--title-xs-font-size'),
('--tomato'),
('--transform-origin-near'),
('--transform-origin-far'),
('--twitter'),
('--violet'),
('--white'),
('--width-lg'),
('--width-md'),
('--width-sm'),
('--yellow'),
('0'),
('70%'),
('80%'),
('90%'),
('100%'),
('absolute'),
('alternate'),
('alternate-reverse'),
('auto'),
('auto/repeat(2, auto)'),
('auto/repeat(3, auto)'),
('auto/repeat(4, auto)'),
('auto/repeat(5, auto)'),
('auto/repeat(6, auto)'),
('auto/repeat(7, auto)'),
('auto/repeat(8, auto)'),
('auto/repeat(9, auto)'),
('auto/repeat(10, auto)'),
('auto/repeat(11, auto)'),
('auto/repeat(12, auto)'),
('backwards'),
('block'),
('bold'),
('center'),
('collapse'),
('column'),
('column-reverse'),
('crosshair'),
('dashed'),
('dotted'),
('double'),
('fixed'),
('flex'),
('forwards'),
('grid'),
('groove'),
('help'),
('infinite'),
('inline'),
('inline-block'),
('inline-flex'),
('inline-table'),
('inset'),
('italic'),
('justify'),
('left'),
('line-through'),
('linear'),
('normal'),
('no-wrap'),
('none'),
('not-allowed'),
('outset'),
('overline'),
('pointer'),
('relative'),
('reverse'),
('ridge'),
('right'),
('rotate'),
('rotate3d'),
('rotateX'),
('rotateY'),
('rotateZ'),
('row'),
('row-reverse'),
('scale'),
('scale3d'),
('scaleX'),
('scaleY'),
('scaleZ'),
('separate'),
('skew'),
('skewX'),
('skewY'),
('solid'),
('space-around'),
('space-between'),
('space-evenly'),
('static'),
('sticky'),
('stretch'),
('table-caption'),
('table-cell'),
('table-column'),
('table-row'),
('translate'),
('translate3d'),
('translateX'),
('translateY'),
('translateZ'),
('underline'),
('wavy'),
('wrap'),
('wrap-reverse'),
('--btn-circle-padding-top'),
('--btn-round-padding-top'),
('--btn-square-padding-top'),
('oblique');

INSERT INTO Media
(media,     screen)
VALUES
('xs',      'All'),
('sm',      'min-width: 576px'),
('md',      'min-width: 768px'),
('lg',      'min-width: 992px'),
('xl',      'min-width: 1200px');

INSERT INTO Class
(class,                 part_id,  source_id,    property_id,  valor_id,     media_id, concat)
VALUES
('container',           1,        4,            38,           603,          1,        1),
('container-70xs',      1,        4,            44,           596,          1,        1),
('container-80xs',      1,        4,            44,           597,          1,        1),
('container-90xs',      1,        4,            44,           598,          1,        1),
('container-70sm',      1,        4,            44,           596,          2,        1),
('container-80sm',      1,        4,            44,           597,          2,        1),
('container-90sm',      1,        4,            44,           598,          2,        1),
('container-70md',      1,        4,            44,           596,          3,        1),
('container-80md',      1,        4,            44,           597,          3,        1),
('container-90md',      1,        4,            44,           598,          3,        1),
('container-70lg',      1,        4,            44,           596,          4,        1),
('container-80lg',      1,        4,            44,           597,          4,        1),
('container-90lg',      1,        4,            44,           598,          4,        1),
('container-70xl',      1,        4,            44,           596,          5,        1),
('container-80xl',      1,        4,            44,           597,          5,        1),
('container-90xl',      1,        4,            44,           598,          5,        1),
('mar-all-none',        1,        4,            38,           367,          1,        0),
('mar-all-sm',          1,        4,            38,           371,          1,        0),
('mar-all-md',          1,        4,            38,           366,          1,        0),
('mar-all-lg',          1,        4,            38,           365,          1,        0),
('mar-bot-none',        1,        4,            39,           367,          1,        0),
('mar-bot-sm',          1,        4,            39,           361,          1,        0),
('mar-bot-md',          1,        4,            39,           360,          1,        0),
('mar-bot-lg',          1,        4,            39,           359,          1,        0),
('mar-left-none',       1,        4,            40,           367,          1,        0),
('mar-left-sm',         1,        4,            40,           364,          1,        0),
('mar-left-md',         1,        4,            40,           363,          1,        0),
('mar-left-lg',         1,        4,            40,           362,          1,        0),
('mar-right-none',      1,        4,            41,           367,          1,        0),
('mar-right-sm',        1,        4,            41,           370,          1,        0),
('mar-right-md',        1,        4,            41,           369,          1,        0),
('mar-right-lg',        1,        4,            41,           368,          1,        0),
('mar-top-none',        1,        4,            42,           367,          1,        0),
('mar-top-sm',          1,        4,            42,           374,          1,        0),
('mar-top-md',          1,        4,            42,           373,          1,        0),
('mar-top-lg',          1,        4,            42,           372,          1,        0),
('pad-all-none',        1,        4,            51,           459,          1,        0),
('pad-all-sm',          1,        4,            51,           463,          1,        0),
('pad-all-md',          1,        4,            51,           458,          1,        0),
('pad-all-lg',          1,        4,            51,           457,          1,        0),
('pad-bot-none',        1,        4,            52,           459,          1,        0),
('pad-bot-sm',          1,        4,            52,           453,          1,        0),
('pad-bot-md',          1,        4,            52,           452,          1,        0),
('pad-bot-lg',          1,        4,            52,           451,          1,        0),
('pad-left-none',       1,        4,            53,           459,          1,        0),
('pad-left-sm',         1,        4,            53,           456,          1,        0),
('pad-left-md',         1,        4,            53,           455,          1,        0),
('pad-left-lg',         1,        4,            53,           454,          1,        0),
('pad-right-none',      1,        4,            54,           459,          1,        0),
('pad-right-sm',        1,        4,            54,           462,          1,        0),
('pad-right-md',        1,        4,            54,           461,          1,        0),
('pad-right-lg',        1,        4,            54,           460,          1,        0),
('pad-top-none',        1,        4,            55,           459,          1,        0),
('pad-top-sm',          1,        4,            55,           466,          1,        0),
('pad-top-md',          1,        4,            55,           465,          1,        0),
('pad-top-lg',          1,        4,            55,           464,          1,        0),
('height-sm',           1,        4,            34,           325,          1,        0),
('height-md',           1,        4,            34,           324,          1,        0),
('height-lg',           1,        4,            34,           323,          1,        0),
('max-h-sm',            1,        4,            43,           378,          1,        0),
('max-h-md',            1,        4,            43,           377,          1,        0),
('max-h-lg',            1,        4,            43,           376,          1,        0),
('min-h-sm',            1,        4,            45,           412,          1,        0),
('min-h-md',            1,        4,            45,           411,          1,        0),
('min-h-lg',            1,        4,            45,           410,          1,        0),
('width-sm',            1,        4,            74,           593,          1,        0),
('width-md',            1,        4,            74,           592,          1,        0),
('width-lg',            1,        4,            74,           591,          1,        0),
('max-w-sm',            1,        4,            44,           381,          1,        0),
('max-w-md',            1,        4,            44,           380,          1,        0),
('max-w-lg',            1,        4,            44,           379,          1,        0),
('min-w-sm',            1,        4,            46,           415,          1,        0),
('min-w-md',            1,        4,            46,           414,          1,        0),
('min-w-lg',            1,        4,            46,           413,          1,        0),
('font-bold',           1,        5,            31,           617,          1,        0),
('font-italic',         1,        5,            30,           638,          1,        0),
('font-normal',         1,        5,            1,            643,          1,        0),
('font-oblique',        1,        5,            30,           693,          1,        0),
('text-center',         1,        5,            62,           618,          1,        0),
('text-justify',        1,        5,            62,           639,          1,        0),
('text-left',           1,        5,            62,           640,          1,        0),
('text-right',          1,        5,            62,           653,          1,        0),
('cursor-cross',        1,        5,            24,           622,          1,        0),
('cursor-help',         1,        5,            24,           631,          1,        0),
('cursor-none',         1,        5,            24,           645,          1,        0),
('cursor-hand',         1,        5,            24,           649,          1,        0),
('grid',                2,        6,            1,            2,            1,        1),
('fluid',               2,        6,            1,            2,            1,        1),
('grid-2xs',            2,        6,            33,           604,          1,        1),
('fluid-2xs',           2,        6,            33,           604,          1,        1),
('grid-3xs',            2,        6,            33,           605,          1,        1),
('fluid-3xs',           2,        6,            33,           605,          1,        1),
('grid-4xs',            2,        6,            33,           606,          1,        1),
('fluid-4xs',           2,        6,            33,           606,          1,        1),
('grid-5xs',            2,        6,            33,           607,          1,        1),
('fluid-5xs',           2,        6,            33,           607,          1,        1),
('grid-6xs',            2,        6,            33,           608,          1,        1),
('fluid-6xs',           2,        6,            33,           608,          1,        1),
('grid-7xs',            2,        6,            33,           609,          1,        1),
('fluid-7xs',           2,        6,            33,           609,          1,        1),
('grid-8xs',            2,        6,            33,           610,          1,        1),
('fluid-8xs',           2,        6,            33,           610,          1,        1),
('grid-9xs',            2,        6,            33,           611,          1,        1),
('fluid-9xs',           2,        6,            33,           611,          1,        1),
('grid-10xs',           2,        6,            33,           612,          1,        1),
('fluid-10xs',          2,        6,            33,           612,          1,        1),
('grid-11xs',           2,        6,            33,           613,          1,        1),
('fluid-11xs',          2,        6,            33,           613,          1,        1),
('grid-12xs',           2,        6,            33,           614,          1,        1),
('fluid-12xs',          2,        6,            33,           614,          1,        1),
('gap-small-xs',        2,        6,            32,           317,          1,        1),
('gap-medium-xs',       2,        6,            32,           318,          1,        1),
('gap-large-xs',        2,        6,            32,           319,          1,        1),
('grid-2sm',            2,        6,            33,           604,          2,        1),
('fluid-2sm',           2,        6,            33,           604,          2,        1),
('grid-3sm',            2,        6,            33,           605,          2,        1),
('fluid-3sm',           2,        6,            33,           605,          2,        1),
('grid-4sm',            2,        6,            33,           606,          2,        1),
('fluid-4sm',           2,        6,            33,           606,          2,        1),
('grid-5sm',            2,        6,            33,           607,          2,        1),
('fluid-5sm',           2,        6,            33,           607,          2,        1),
('grid-6sm',            2,        6,            33,           608,          2,        1),
('fluid-6sm',           2,        6,            33,           608,          2,        1),
('grid-7sm',            2,        6,            33,           609,          2,        1),
('fluid-7sm',           2,        6,            33,           609,          2,        1),
('grid-8sm',            2,        6,            33,           610,          2,        1),
('fluid-8sm',           2,        6,            33,           610,          2,        1),
('grid-9sm',            2,        6,            33,           611,          2,        1),
('fluid-9sm',           2,        6,            33,           611,          2,        1),
('grid-10sm',           2,        6,            33,           612,          2,        1),
('fluid-10sm',          2,        6,            33,           612,          2,        1),
('grid-11sm',           2,        6,            33,           613,          2,        1),
('fluid-11sm',          2,        6,            33,           613,          2,        1),
('grid-12sm',           2,        6,            33,           614,          2,        1),
('fluid-12sm',          2,        6,            33,           614,          2,        1),
('gap-small-sm',        2,        6,            32,           311,          2,        1),
('gap-medium-sm',       2,        6,            32,           312,          2,        1),
('gap-large-sm',        2,        6,            32,           313,          2,        1),
('grid-2md',            2,        6,            33,           604,          3,        1),
('fluid-2md',           2,        6,            33,           604,          3,        1),
('grid-3md',            2,        6,            33,           605,          3,        1),
('fluid-3md',           2,        6,            33,           605,          3,        1),
('grid-4md',            2,        6,            33,           606,          3,        1),
('fluid-4md',           2,        6,            33,           606,          3,        1),
('grid-5md',            2,        6,            33,           607,          3,        1),
('fluid-5md',           2,        6,            33,           607,          3,        1),
('grid-6md',            2,        6,            33,           608,          3,        1),
('fluid-6md',           2,        6,            33,           608,          3,        1),
('grid-7md',            2,        6,            33,           609,          3,        1),
('fluid-7md',           2,        6,            33,           609,          3,        1),
('grid-8md',            2,        6,            33,           610,          3,        1),
('fluid-8md',           2,        6,            33,           610,          3,        1),
('grid-9md',            2,        6,            33,           611,          3,        1),
('fluid-9md',           2,        6,            33,           611,          3,        1),
('grid-10md',           2,        6,            33,           612,          3,        1),
('fluid-10md',          2,        6,            33,           612,          3,        1),
('grid-11md',           2,        6,            33,           613,          3,        1),
('fluid-11md',          2,        6,            33,           613,          3,        1),
('grid-12md',           2,        6,            33,           614,          3,        1),
('fluid-12md',          2,        6,            33,           614,          3,        1),
('gap-small-md',        2,        6,            32,           308,          3,        1),
('gap-medium-md',       2,        6,            32,           309,          3,        1),
('gap-large-md',        2,        6,            32,           310,          3,        1),
('grid-2lg',            2,        6,            33,           604,          4,        1),
('fluid-2lg',           2,        6,            33,           604,          4,        1),
('grid-3lg',            2,        6,            33,           605,          4,        1),
('fluid-3lg',           2,        6,            33,           605,          4,        1),
('grid-4lg',            2,        6,            33,           606,          4,        1),
('fluid-4lg',           2,        6,            33,           606,          4,        1),
('grid-5lg',            2,        6,            33,           607,          4,        1),
('fluid-5lg',           2,        6,            33,           607,          4,        1),
('grid-6lg',            2,        6,            33,           608,          4,        1),
('fluid-6lg',           2,        6,            33,           608,          4,        1),
('grid-7lg',            2,        6,            33,           609,          4,        1),
('fluid-7lg',           2,        6,            33,           609,          4,        1),
('grid-8lg',            2,        6,            33,           610,          4,        1),
('fluid-8lg',           2,        6,            33,           610,          4,        1),
('grid-9lg',            2,        6,            33,           611,          4,        1),
('fluid-9lg',           2,        6,            33,           611,          4,        1),
('grid-10lg',           2,        6,            33,           612,          4,        1),
('fluid-10lg',          2,        6,            33,           612,          4,        1),
('grid-11lg',           2,        6,            33,           613,          4,        1),
('fluid-11lg',          2,        6,            33,           613,          4,        1),
('grid-12lg',           2,        6,            33,           614,          4,        1),
('fluid-12lg',          2,        6,            33,           614,          4,        1),
('gap-small-lg',        2,        6,            32,           305,          4,        1),
('gap-medium-lg',       2,        6,            32,           306,          4,        1),
('gap-large-lg',        2,        6,            32,           307,          4,        1),
('grid-2xl',            2,        6,            33,           604,          5,        1),
('fluid-2xl',           2,        6,            33,           604,          5,        1),
('grid-3xl',            2,        6,            33,           605,          5,        1),
('fluid-3xl',           2,        6,            33,           605,          5,        1),
('grid-4xl',            2,        6,            33,           606,          5,        1),
('fluid-4xl',           2,        6,            33,           606,          5,        1),
('grid-5xl',            2,        6,            33,           607,          5,        1),
('fluid-5xl',           2,        6,            33,           607,          5,        1),
('grid-6xl',            2,        6,            33,           608,          5,        1),
('fluid-6xl',           2,        6,            33,           608,          5,        1),
('grid-7xl',            2,        6,            33,           609,          5,        1),
('fluid-7xl',           2,        6,            33,           609,          5,        1),
('grid-8xl',            2,        6,            33,           610,          5,        1),
('fluid-8xl',           2,        6,            33,           610,          5,        1),
('grid-9xl',            2,        6,            33,           611,          5,        1),
('fluid-9xl',           2,        6,            33,           611,          5,        1),
('grid-10xl',           2,        6,            33,           612,          5,        1),
('fluid-10xl',          2,        6,            33,           612,          5,        1),
('grid-11xl',           2,        6,            33,           613,          5,        1),
('fluid-11xl',          2,        6,            33,           613,          5,        1),
('grid-12xl',           2,        6,            33,           614,          5,        1),
('fluid-12xl',          2,        6,            33,           614,          5,        1),
('gap-small-xl',        2,        6,            32,           314,          5,        1),
('gap-medium-xl',       2,        6,            32,           315,          5,        1),
('gap-large-xl',        2,        6,            32,           316,          5,        1),
('flex',                2,        7,            1,            2,            1,        1),
('column',              2,        7,            1,            179,          1,        0),
('col-inverse',         2,        7,            27,           689,          1,        0),
('col-nowrap',          2,        7,            27,           644,          1,        0),
('col-reverse',         2,        7,            26,           621,          1,        0),
('row',                 2,        7,            1,            478,          1,        0),
('row-inverse',         2,        7,            27,           689,          1,        0),
('row-nowrap',          2,        7,            27,           644,          1,        0),
('row-reverse',         2,        7,            26,           660,          1,        0),
('flex-2xs',            2,        7,            1,            1,            1,        1),
('flex-3xs',            2,        7,            1,            1,            1,        1),
('flex-4xs',            2,        7,            1,            1,            1,        1),
('flex-5xs',            2,        7,            1,            1,            1,        1),
('flex-6xs',            2,        7,            1,            1,            1,        1),
('flex-7xs',            2,        7,            1,            1,            1,        1),
('flex-8xs',            2,        7,            1,            1,            1,        1),
('flex-9xs',            2,        7,            1,            1,            1,        1),
('flex-10xs',           2,        7,            1,            1,            1,        1),
('flex-11xs',           2,        7,            1,            1,            1,        1),
('flex-12xs',           2,        7,            1,            1,            1,        1),
('flex-2sm',            2,        7,            1,            1,            2,        1),
('flex-3sm',            2,        7,            1,            1,            2,        1),
('flex-4sm',            2,        7,            1,            1,            2,        1),
('flex-5sm',            2,        7,            1,            1,            2,        1),
('flex-6sm',            2,        7,            1,            1,            2,        1),
('flex-7sm',            2,        7,            1,            1,            2,        1),
('flex-8sm',            2,        7,            1,            1,            2,        1),
('flex-9sm',            2,        7,            1,            1,            2,        1),
('flex-10sm',           2,        7,            1,            1,            2,        1),
('flex-11sm',           2,        7,            1,            1,            2,        1),
('flex-12sm',           2,        7,            1,            1,            2,        1),
('flex-2md',            2,        7,            1,            1,            3,        1),
('flex-3md',            2,        7,            1,            1,            3,        1),
('flex-4md',            2,        7,            1,            1,            3,        1),
('flex-5md',            2,        7,            1,            1,            3,        1),
('flex-6md',            2,        7,            1,            1,            3,        1),
('flex-7md',            2,        7,            1,            1,            3,        1),
('flex-8md',            2,        7,            1,            1,            3,        1),
('flex-9md',            2,        7,            1,            1,            3,        1),
('flex-10md',           2,        7,            1,            1,            3,        1),
('flex-11md',           2,        7,            1,            1,            3,        1),
('flex-12md',           2,        7,            1,            1,            3,        1),
('flex-2lg',            2,        7,            1,            1,            4,        1),
('flex-3lg',            2,        7,            1,            1,            4,        1),
('flex-4lg',            2,        7,            1,            1,            4,        1),
('flex-5lg',            2,        7,            1,            1,            4,        1),
('flex-6lg',            2,        7,            1,            1,            4,        1),
('flex-7lg',            2,        7,            1,            1,            4,        1),
('flex-8lg',            2,        7,            1,            1,            4,        1),
('flex-9lg',            2,        7,            1,            1,            4,        1),
('flex-10lg',           2,        7,            1,            1,            4,        1),
('flex-11lg',           2,        7,            1,            1,            4,        1),
('flex-12lg',           2,        7,            1,            1,            4,        1),
('flex-2xl',            2,        7,            1,            1,            5,        1),
('flex-3xl',            2,        7,            1,            1,            5,        1),
('flex-4xl',            2,        7,            1,            1,            5,        1),
('flex-5xl',            2,        7,            1,            1,            5,        1),
('flex-6xl',            2,        7,            1,            1,            5,        1),
('flex-7xl',            2,        7,            1,            1,            5,        1),
('flex-8xl',            2,        7,            1,            1,            5,        1),
('flex-9xl',            2,        7,            1,            1,            5,        1),
('flex-10xl',           2,        7,            1,            1,            5,        1),
('flex-11xl',           2,        7,            1,            1,            5,        1),
('flex-12xl',           2,        7,            1,            1,            5,        1),
('placo-around',        2,        8,            56,           671,          1,        0),
('placo-between',       2,        8,            56,           672,          1,        0),
('placo-evenly',        2,        8,            56,           673,          1,        0),
('placo-center',        2,        8,            56,           618,          1,        0),
('placo-stretch',       2,        8,            56,           676,          1,        0),
('placo-start',         2,        8,            56,           468,          1,        0),
('placo-end',           2,        8,            56,           467,          1,        0),
('placo-around-sm',     2,        8,            56,           671,          2,        0),
('placo-between-sm',    2,        8,            56,           672,          2,        0),
('placo-evenly-sm',     2,        8,            56,           673,          2,        0),
('placo-center-sm',     2,        8,            56,           618,          2,        0),
('placo-stretch-sm',    2,        8,            56,           676,          2,        0),
('placo-start-sm',      2,        8,            56,           468,          2,        0),
('placo-end-sm',        2,        8,            56,           467,          2,        0),
('placo-around-md',     2,        8,            56,           671,          3,        0),
('placo-between-md',    2,        8,            56,           672,          3,        0),
('placo-evenly-md',     2,        8,            56,           673,          3,        0),
('placo-center-md',     2,        8,            56,           618,          3,        0),
('placo-stretch-md',    2,        8,            56,           676,          3,        0),
('placo-start-md',      2,        8,            56,           468,          3,        0),
('placo-end-md',        2,        8,            56,           467,          3,        0),
('placo-around-lg',     2,        8,            56,           671,          4,        0),
('placo-between-lg',    2,        8,            56,           672,          4,        0),
('placo-evenly-lg',     2,        8,            56,           673,          4,        0),
('placo-center-lg',     2,        8,            56,           618,          4,        0),
('placo-stretch-lg',    2,        8,            56,           676,          4,        0),
('placo-start-lg',      2,        8,            56,           468,          4,        0),
('placo-end-lg',        2,        8,            56,           467,          4,        0),
('placo-around-xl',     2,        8,            56,           671,          5,        0),
('placo-between-xl',    2,        8,            56,           672,          5,        0),
('placo-evenly-xl',     2,        8,            56,           673,          5,        0),
('placo-center-xl',     2,        8,            56,           618,          5,        0),
('placo-stretch-xl',    2,        8,            56,           676,          5,        0),
('placo-start-xl',      2,        8,            56,           468,          5,        0),
('placo-end-xl',        2,        8,            56,           467,          5,        0),
('plait-base',          2,        8,            57,           469,          5,        0),
('plait-normal',        2,        8,            57,           643,          1,        0),
('plait-center',        2,        8,            57,           618,          1,        0),
('plait-stretch',       2,        8,            57,           676,          1,        0),
('plait-start',         2,        8,            57,           471,          1,        0),
('plait-end',           2,        8,            57,           470,          1,        0),
('plait-base-sm',       2,        8,            57,           469,          2,        0),
('plait-normal-sm',     2,        8,            57,           643,          2,        0),
('plait-center-sm',     2,        8,            57,           618,          2,        0),
('plait-stretch-sm',    2,        8,            57,           676,          2,        0),
('plait-start-sm',      2,        8,            57,           471,          2,        0),
('plait-end-sm',        2,        8,            57,           470,          2,        0),
('plait-base-md',       2,        8,            57,           469,          3,        0),
('plait-normal-md',     2,        8,            57,           643,          3,        0),
('plait-center-md',     2,        8,            57,           618,          3,        0),
('plait-stretch-md',    2,        8,            57,           676,          3,        0),
('plait-start-md',      2,        8,            57,           471,          3,        0),
('plait-end-md',        2,        8,            57,           470,          3,        0),
('plait-base-lg',       2,        8,            57,           469,          4,        0),
('plait-normal-lg',     2,        8,            57,           643,          4,        0),
('plait-center-lg',     2,        8,            57,           618,          4,        0),
('plait-stretch-lg',    2,        8,            57,           676,          4,        0),
('plait-start-lg',      2,        8,            57,           471,          4,        0),
('plait-end-lg',        2,        8,            57,           470,          4,        0),
('plait-base-xl',       2,        8,            57,           469,          5,        0),
('plait-normal-xl',     2,        8,            57,           643,          5,        0),
('plait-center-xl',     2,        8,            57,           618,          5,        0),
('plait-stretch-xl',    2,        8,            57,           676,          5,        0),
('plait-start-xl',      2,        8,            57,           471,          5,        0),
('plait-end-xl',        2,        8,            57,           470,          5,        0),
('plase-auto',          2,        8,            58,           603,          1,        0),
('plase-base',          2,        8,            58,           472,          1,        0),
('plase-normal',        2,        8,            58,           643,          1,        0),
('plase-center',        2,        8,            58,           618,          1,        0),
('plase-stretch',       2,        8,            58,           676,          1,        0),
('plase-start',         2,        8,            58,           474,          1,        0),
('plase-end',           2,        8,            58,           473,          1,        0),
('plase-auto-sm',       2,        8,            58,           603,          2,        0),
('plase-base-sm',       2,        8,            58,           472,          2,        0),
('plase-normal-sm',     2,        8,            58,           643,          2,        0),
('plase-center-sm',     2,        8,            58,           618,          2,        0),
('plase-stretch-sm',    2,        8,            58,           676,          2,        0),
('plase-start-sm',      2,        8,            58,           474,          2,        0),
('plase-end-sm',        2,        8,            58,           473,          2,        0),
('plase-auto-md',       2,        8,            58,           603,          3,        0),
('plase-base-md',       2,        8,            58,           472,          3,        0),
('plase-normal-md',     2,        8,            58,           643,          3,        0),
('plase-center-md',     2,        8,            58,           618,          3,        0),
('plase-stretch-md',    2,        8,            58,           676,          3,        0),
('plase-start-md',      2,        8,            58,           474,          3,        0),
('plase-end-md',        2,        8,            58,           473,          3,        0),
('plase-auto-lg',       2,        8,            58,           603,          4,        0),
('plase-base-lg',       2,        8,            58,           472,          4,        0),
('plase-normal-lg',     2,        8,            58,           643,          4,        0),
('plase-center-lg',     2,        8,            58,           618,          4,        0),
('plase-stretch-lg',    2,        8,            58,           676,          4,        0),
('plase-start-lg',      2,        8,            58,           474,          4,        0),
('plase-end-lg',        2,        8,            58,           473,          4,        0),
('plase-auto-xl',       2,        8,            58,           603,          5,        0),
('plase-base-xl',       2,        8,            58,           472,          5,        0),
('plase-normal-xl',     2,        8,            58,           643,          5,        0),
('plase-center-xl',     2,        8,            58,           618,          5,        0),
('plase-stretch-xl',    2,        8,            58,           676,          5,        0),
('plase-start-xl',      2,        8,            58,           474,          5,        0),
('plase-end-xl',        2,        8,            58,           473,          5,        0),
('btn',                 3,        9,            1,            1,            1,        0),
('button',              3,        9,            1,            1,            1,        0),
('btn-black',           3,        9,            1,            1,            1,        0),
('button-black',        3,        9,            1,            1,            1,        0),
('btn-blue',            3,        9,            1,            1,            1,        0),
('button-blue',         3,        9,            1,            1,            1,        0),
('btn-choco',           3,        9,            1,            1,            1,        0),
('button-choco',        3,        9,            1,            1,            1,        0),
('btn-gray',            3,        9,            1,            1,            1,        0),
('button-gray',         3,        9,            1,            1,            1,        0),
('btn-green',           3,        9,            1,            1,            1,        0),
('button-green',        3,        9,            1,            1,            1,        0),
('btn-jade',            3,        9,            1,            1,            1,        0),
('button-jade',         3,        9,            1,            1,            1,        0),
('btn-khaki',           3,        9,            1,            1,            1,        0),
('button-khaki',        3,        9,            1,            1,            1,        0),
('btn-maroon',          3,        9,            1,            1,            1,        0),
('button-maroon',       3,        9,            1,            1,            1,        0),
('btn-orange',          3,        9,            1,            1,            1,        0),
('button-orange',       3,        9,            1,            1,            1,        0),
('btn-purple',          3,        9,            1,            1,            1,        0),
('button-purple',       3,        9,            1,            1,            1,        0),
('btn-red',             3,        9,            1,            1,            1,        0),
('button-red',          3,        9,            1,            1,            1,        0),
('btn-salmon',          3,        9,            1,            1,            1,        0),
('button-salmon',       3,        9,            1,            1,            1,        0),
('btn-silver',          3,        9,            1,            1,            1,        0),
('button-silver',       3,        9,            1,            1,            1,        0),
('btn-sky',             3,        9,            1,            1,            1,        0),
('button-sky',          3,        9,            1,            1,            1,        0),
('btn-tomato',          3,        9,            1,            1,            1,        0),
('button-tomato',       3,        9,            1,            1,            1,        0),
('btn-violet',          3,        9,            1,            1,            1,        0),
('button-violet',       3,        9,            1,            1,            1,        0),
('btn-white',           3,        9,            1,            1,            1,        0),
('button-white',        3,        9,            1,            1,            1,        0),
('btn-yellow',          3,        9,            1,            1,            1,        0),
('button-yellow',       3,        9,            1,            1,            1,        0),
('btn-fb',              3,        9,            1,            1,            1,        0),
('button-fb',           3,        9,            1,            1,            1,        0),
('btn-github',          3,        9,            1,            1,            1,        0),
('button-github',       3,        9,            1,            1,            1,        0),
('btn-jsd',             3,        9,            1,            1,            1,        0),
('button-jsd',          3,        9,            1,            1,            1,        0),
('btn-in',              3,        9,            1,            1,            1,        0),
('button-in',           3,        9,            1,            1,            1,        0),
('btn-npm',             3,        9,            1,            1,            1,        0),
('button-npm',          3,        9,            1,            1,            1,        0),
('btn-stack',           3,        9,            1,            1,            1,        0),
('button-stack',        3,        9,            1,            1,            1,        0),
('btn-tw',              3,        9,            1,            1,            1,        0),
('button-tw',           3,        9,            1,            1,            1,        0),
('btn-amethyst',        3,        9,            1,            1,            1,        0),
('button-amethyst',     3,        9,            1,            1,            1,        0),
('btn-citrine',         3,        9,            1,            1,            1,        0),
('button-citrine',      3,        9,            1,            1,            1,        0),
('btn-emerald',         3,        9,            1,            1,            1,        0),
('button-emerald',      3,        9,            1,            1,            1,        0),
('btn-obsidian',        3,        9,            1,            1,            1,        0),
('button-obsidian',     3,        9,            1,            1,            1,        0),
('btn-quartz',          3,        9,            1,            1,            1,        0),
('button-quartz',       3,        9,            1,            1,            1,        0),
('btn-ruby',            3,        9,            1,            1,            1,        0),
('button-ruby',         3,        9,            1,            1,            1,        0),
('btn-sapphire',        3,        9,            1,            1,            1,        0),
('button-sapphire',     3,        9,            1,            1,            1,        0),
('btn-xs',              3,        9,            1,            1,            1,        0),
('button-xs',           3,        9,            1,            1,            1,        0),
('btn-sm',              3,        9,            1,            1,            1,        0),
('button-sm',           3,        9,            1,            1,            1,        0),
('btn-lg',              3,        9,            1,            1,            1,        0),
('button-lg',           3,        9,            1,            1,            1,        0),
('btn-xl',              3,        9,            1,            1,            1,        0),
('button-xl',           3,        9,            1,            1,            1,        0),
('btn-circle',          3,        9,            1,            1,            1,        0),
('button-circle',       3,        9,            1,            1,            1,        0),
('btn-round',           3,        9,            1,            1,            1,        0),
('button-round',        3,        9,            1,            1,            1,        0),
('btn-square',          3,        9,            1,            1,            1,        0),
('button-square',       3,        9,            1,            1,            1,        0),
('card',                3,        10,           1,            1,            1,        0),
('card-blue',           3,        10,           1,            1,            1,        0),
('card-green',          3,        10,           1,            1,            1,        0),
('card-red',            3,        10,           1,            1,            1,        0),
('card-purple',         3,        10,           1,            1,            1,        0),
('card-yellow',         3,        10,           1,            1,            1,        0),
('foot',                3,        11,           1,            1,            1,        0),
('form',                3,        12,           1,            1,            1,        0),
('gallery',             3,        13,           1,            1,            1,        0),
('menu',                3,        14,           1,            1,            1,        0),
('navbar',              3,        15,           1,            1,            1,        0),
('slider',              3,        16,           1,            1,            1,        0),
('table',               3,        17,           1,            1,            1,        0),
('anima',               4,        18,           1,            1,            1,        0),
('anima-rota',          4,        18,           8,            654,          1,        0),
('anima-rota3d',        4,        18,           8,            655,          1,        0),
('anima-rotax',         4,        18,           8,            656,          1,        0),
('anima-rotay',         4,        18,           8,            657,          1,        0),
('anima-rotaz',         4,        18,           8,            658,          1,        0),
('anima-scal',          4,        18,           8,            661,          1,        0),
('anima-scal3d',        4,        18,           8,            662,          1,        0),
('anima-scalx',         4,        18,           8,            663,          1,        0),
('anima-scaly',         4,        18,           8,            664,          1,        0),
('anima-scalz',         4,        18,           8,            665,          1,        0),
('anima-skew',          4,        18,           8,            667,          1,        0),
('anima-skewx',         4,        18,           8,            668,          1,        0),
('anima-skewy',         4,        18,           8,            669,          1,        0),
('anima-tran',          4,        18,           8,            681,          1,        0),
('anima-tran3d',        4,        18,           8,            682,          1,        0),
('anima-tranx',         4,        18,           8,            683,          1,        0),
('anima-trany',         4,        18,           8,            684,          1,        0),
('anima-tranz',         4,        18,           8,            685,          1,        0),
('anima-xs',            4,        18,           5,            10,           1,        0),
('anima-sm',            4,        18,           5,            11,           1,        0),
('anima-md',            4,        18,           5,            12,           1,        0),
('anima-lg',            4,        18,           5,            13,           1,        0),
('anima-xl',            4,        18,           5,            14,           1,        0),
('anima-linear',        4,        18,           9,            642,          1,        0),
('anima-ease',          4,        18,           9,            22,           1,        0),
('anima-steps',         4,        18,           9,            23,           1,        0),
('anima-bezier',        4,        18,           9,            21,           1,        0),
('anima-few',           4,        18,           7,            17,           1,        0),
('anima-many',          4,        18,           7,            18,           1,        0),
('anima-loop',          4,        18,           7,            632,          1,        0),
('anima-alter',         4,        18,           4,            601,          1,        0),
('anima-rever',         4,        18,           4,            651,          1,        0),
('anima-altrev',        4,        18,           4,            602,          1,        0),
('anima-small',         4,        18,           3,            7,            1,        0),
('anima-medium',        4,        18,           3,            6,            1,        0),
('anima-large',         4,        18,           3,            5,            1,        0),
('anima-back',          4,        18,           6,            615,          1,        0),
('anima-front',         4,        18,           6,            628,          1,        0),
('anima-far',           4,        18,           71,           587,          1,        0),
('anima-near',          4,        18,           71,           586,          1,        0),
('bg-black',            4,        19,           10,           25,           1,        0),
('bg-blue',             4,        19,           10,           26,           1,        0),
('bg-choco',            4,        19,           10,           172,          1,        0),
('bg-gray',             4,        19,           10,           321,          1,        0),
('bg-green',            4,        19,           10,           322,          1,        0),
('bg-jade',             4,        19,           10,           329,          1,        0),
('bg-khaki',            4,        19,           10,           351,          1,        0),
('bg-maroon',           4,        19,           10,           375,          1,        0),
('bg-orange',           4,        19,           10,           450,          1,        0),
('bg-purple',           4,        19,           10,           475,          1,        0),
('bg-red',              4,        19,           10,           477,          1,        0),
('bg-salmon',           4,        19,           10,           480,          1,        0),
('bg-silver',           4,        19,           10,           482,          1,        0),
('bg-sky',              4,        19,           10,           483,          1,        0),
('bg-tomato',           4,        19,           10,           585,          1,        0),
('bg-violet',           4,        19,           10,           589,          1,        0),
('bg-white',            4,        19,           10,           590,          1,        0),
('bg-yellow',           4,        19,           10,           594,          1,        0),
('bg-fb',               4,        19,           10,           181,          1,        0),
('bg-github',           4,        19,           10,           320,          1,        0),
('bg-in',               4,        19,           10,           353,          1,        0),
('bg-jsd',              4,        19,           10,           330,          1,        0),
('bg-npm',              4,        19,           10,           448,          1,        0),
('bg-stack',            4,        19,           10,           523,          1,        0),
('bg-tw',               4,        19,           10,           588,          1,        0),
('amethyst',            4,        19,           10,           3,            1,        0),
('citrine',             4,        19,           10,           173,          1,        0),
('emerald',             4,        19,           10,           180,          1,        0),
('quartz',              4,        19,           10,           476,          1,        0),
('obsidian',            4,        19,           10,           449,          1,        0),
('ruby',                4,        19,           10,           479,          1,        0),
('sapphire',            4,        19,           10,           481,          1,        0),
('bord',                4,        20,           1,            1,            1,        0),
('bord-dash',           4,        20,           16,           623,          1,        0),
('bord-dot',            4,        20,           16,           624,          1,        0),
('bord-double',         4,        20,           16,           625,          1,        0),
('bord-groove',         4,        20,           16,           630,          1,        0),
('bord-inset',          4,        20,           16,           637,          1,        0),
('bord-outset',         4,        20,           16,           647,          1,        0),
('bord-ridge',          4,        20,           16,           652,          1,        0),
('bord-solid',          4,        20,           16,           670,          1,        0),
('bord-sm',             4,        20,           17,           41,           1,        0),
('bord-md',             4,        20,           17,           40,           1,        0),
('bord-lg',             4,        20,           17,           39,           1,        0),
('bord-black',          4,        20,           13,           25,           1,        0),
('bord-blue',           4,        20,           13,           26,           1,        0),
('bord-gray',           4,        20,           13,           321,          1,        0),
('bord-green',          4,        20,           13,           322,          1,        0),
('bord-maroon',         4,        20,           13,           375,          1,        0),
('bord-orange',         4,        20,           13,           450,          1,        0),
('bord-purple',         4,        20,           13,           475,          1,        0),
('bord-red',            4,        20,           13,           477,          1,        0),
('bord-white',          4,        20,           13,           590,          1,        0),
('bord-yellow',         4,        20,           13,           594,          1,        0),
('bord-circle',         4,        20,           14,           34,           1,        0),
('bord-round',          4,        20,           14,           35,           1,        0),
('bord-square',         4,        20,           14,           36,           1,        0),
('color-black',         4,        21,           22,           25,           1,        0),
('color-blue',          4,        21,           22,           26,           1,        0),
('color-choco',         4,        21,           22,           172,          1,        0),
('color-gray',          4,        21,           22,           321,          1,        0),
('color-green',         4,        21,           22,           322,          1,        0),
('color-jade',          4,        21,           22,           329,          1,        0),
('color-khaki',         4,        21,           22,           351,          1,        0),
('color-maroon',        4,        21,           22,           375,          1,        0),
('color-orange',        4,        21,           22,           450,          1,        0),
('color-purple',        4,        21,           22,           475,          1,        0),
('color-red',           4,        21,           22,           477,          1,        0),
('color-salmon',        4,        21,           22,           480,          1,        0),
('color-silver',        4,        21,           22,           482,          1,        0),
('color-sky',           4,        21,           22,           483,          1,        0),
('color-tomato',        4,        21,           22,           585,          1,        0),
('color-violet',        4,        21,           22,           589,          1,        0),
('color-white',         4,        21,           22,           590,          1,        0),
('color-yellow',        4,        21,           22,           594,          1,        0),
('color-fb',            4,        21,           22,           181,          1,        0),
('color-github',        4,        21,           22,           320,          1,        0),
('color-in',            4,        21,           22,           353,          1,        0),
('color-jsd',           4,        21,           22,           330,          1,        0),
('color-npm',           4,        21,           22,           448,          1,        0),
('color-stack',         4,        21,           22,           523,          1,        0),
('color-tw',            4,        21,           22,           588,          1,        0),
('deco',                4,        22,           1,            1,            1,        0),
('deco-none',           4,        22,           65,           645,          1,        0),
('deco-under',          4,        22,           65,           686,          1,        0),
('deco-through',        4,        22,           65,           641,          1,        0),
('deco-over',           4,        22,           65,           648,          1,        0),
('deco-solid',          4,        22,           66,           670,          1,        0),
('deco-dash',           4,        22,           66,           623,          1,        0),
('deco-dot',            4,        22,           66,           624,          1,        0),
('deco-double',         4,        22,           66,           625,          1,        0),
('deco-wavy',           4,        22,           66,           687,          1,        0),
('deco-black',          4,        22,           64,           25,           1,        0),
('deco-blue',           4,        22,           64,           26,           1,        0),
('deco-gray',           4,        22,           64,           321,          1,        0),
('deco-green',          4,        22,           64,           322,          1,        0),
('deco-maroon',         4,        22,           64,           375,          1,        0),
('deco-orange',         4,        22,           64,           450,          1,        0),
('deco-purple',         4,        22,           64,           475,          1,        0),
('deco-red',            4,        22,           64,           477,          1,        0),
('deco-white',          4,        22,           64,           590,          1,        0),
('deco-yellow',         4,        22,           64,           594,          1,        0),
('block',               4,        23,           25,           616,          1,        0),
('block-sm',            4,        23,           25,           616,          2,        0),
('block-md',            4,        23,           25,           616,          3,        0),
('block-lg',            4,        23,           25,           616,          4,        0),
('block-xl',            4,        23,           25,           616,          5,        0),
('hide',                4,        23,           25,           645,          1,        0),
('hide-sm',             4,        23,           25,           645,          2,        0),
('hide-md',             4,        23,           25,           645,          3,        0),
('hide-lg',             4,        23,           25,           645,          4,        0),
('hide-xl',             4,        23,           25,           645,          5,        0),
('inblock',             4,        23,           25,           634,          1,        0),
('inblock-sm',          4,        23,           25,           634,          2,        0),
('inblock-md',          4,        23,           25,           634,          3,        0),
('inblock-lg',          4,        23,           25,           634,          4,        0),
('inblock-xl',          4,        23,           25,           634,          5,        0),
('inline',              4,        23,           25,           633,          1,        0),
('inline-sm',           4,        23,           25,           633,          2,        0),
('inline-md',           4,        23,           25,           633,          3,        0),
('inline-lg',           4,        23,           25,           633,          4,        0),
('inline-xl',           4,        23,           25,           633,          5,        0),
('absolute',            4,        24,           59,           600,          1,        0),
('absolute-sm',         4,        24,           59,           600,          2,        0),
('absolute-md',         4,        24,           59,           600,          3,        0),
('absolute-lg',         4,        24,           59,           600,          4,        0),
('absolute-xl',         4,        24,           59,           600,          5,        0),
('fixed',               4,        24,           59,           626,          1,        0),
('fixed-sm',            4,        24,           59,           626,          2,        0),
('fixed-md',            4,        24,           59,           626,          3,        0),
('fixed-lg',            4,        24,           59,           626,          4,        0),
('fixed-xl',            4,        24,           59,           626,          5,        0),
('relative',            4,        24,           59,           650,          1,        0),
('relative-sm',         4,        24,           59,           650,          2,        0),
('relative-md',         4,        24,           59,           650,          3,        0),
('relative-lg',         4,        24,           59,           650,          4,        0),
('relative-xl',         4,        24,           59,           650,          5,        0),
('sticky-xs',           4,        24,           59,           675,          1,        0),
('sticky-sm',           4,        24,           59,           675,          2,        0),
('sticky-md',           4,        24,           59,           675,          3,        0),
('sticky-lg',           4,        24,           59,           675,          4,        0),
('sticky-xl',           4,        24,           59,           675,          5,        0),
('pos-top',             4,        24,           1,            595,          1,        0),
('pos-bot',             4,        24,           1,            595,          1,        0),
('pos-right',           4,        24,           1,            595,          1,        0),
('pos-left',            4,        24,           1,            595,          1,        0),
('pos-top-sm',          4,        24,           1,            595,          2,        0),
('pos-bot-sm',          4,        24,           1,            595,          2,        0),
('pos-right-sm',        4,        24,           1,            595,          2,        0),
('pos-left-sm',         4,        24,           1,            595,          2,        0),
('pos-top-md',          4,        24,           1,            595,          3,        0),
('pos-bot-md',          4,        24,           1,            595,          3,        0),
('pos-right-md',        4,        24,           1,            595,          3,        0),
('pos-left-md',         4,        24,           1,            595,          3,        0),
('pos-top-lg',          4,        24,           1,            595,          4,        0),
('pos-bot-lg',          4,        24,           1,            595,          4,        0),
('pos-right-lg',        4,        24,           1,            595,          4,        0),
('pos-left-lg',         4,        24,           1,            595,          4,        0),
('pos-top-xl',          4,        24,           1,            595,          5,        0),
('pos-bot-xl',          4,        24,           1,            595,          5,        0),
('pos-right-xl',        4,        24,           1,            595,          5,        0),
('pos-left-xl',         4,        24,           1,            595,          5,        0),
('shabox-sm',           4,        25,           19,           48,           1,        0),
('shabox-in-sm',        4,        25,           19,           48,           1,        0),
('shabox-md',           4,        25,           19,           47,           1,        0),
('shabox-in-md',        4,        25,           19,           47,           1,        0),
('shabox-lg',           4,        25,           19,           46,           1,        0),
('shabox-in-lg',        4,        25,           19,           46,           1,        0),
('shabox-blur-all',     4,        25,           19,           42,           1,        0),
('shabox-in-blur-all',  4,        25,           19,           42,           1,        0),
('shabox-blur-sm',      4,        25,           19,           45,           1,        0),
('shabox-in-blur-sm',   4,        25,           19,           45,           1,        0),
('shabox-blur-md',      4,        25,           19,           44,           1,        0),
('shabox-in-blur-md',   4,        25,           19,           44,           1,        0),
('shabox-blur-lg',      4,        25,           19,           43,           1,        0),
('shabox-in-blur-lg',   4,        25,           19,           43,           1,        0),
('shabox-spread-all',   4,        25,           19,           49,           1,        0),
('shabox-in-spread-all',4,        25,           19,           49,           1,        0),
('shabox-spread-sm',    4,        25,           19,           52,           1,        0),
('shabox-in-spread-sm', 4,        25,           19,           52,           1,        0),
('shabox-spread-md',    4,        25,           19,           51,           1,        0),
('shabox-in-spread-md', 4,        25,           19,           51,           1,        0),
('shabox-spread-lg',    4,        25,           19,           50,           1,        0),
('shabox-in-spread-lg', 4,        25,           19,           50,           1,        0),
('shatex-sm',           4,        26,           67,           576,          1,        0),
('shatex-md',           4,        26,           67,           575,          1,        0),
('shatex-lg',           4,        26,           67,           574,          1,        0),
('shatex-blur-all',     4,        26,           67,           570,          1,        0),
('shatex-blur-sm',      4,        26,           67,           573,          1,        0),
('shatex-blur-md',      4,        26,           67,           572,          1,        0),
('shatex-blur-lg',      4,        26,           67,           571,          1,        0);
