USE animadio;

INSERT INTO Part
(part)
VALUES
('global'),
('grid'),
('elements'),
('states');

INSERT INTO Source
(source)
VALUES
('variables'),
('keyframes'),
('init'),
('box'),
('helpers'),
('fluid'),
('flex'),
('place'),
('btn'),
('card'),
('foot'),
('form'),
('gallery'),
('menu'),
('navbar'),
('slider'),
('table'),
('anima'),
('bg'),
('bord'),
('color'),
('deco'),
('display'),
('position'),
('shabox'),
('shatex');

INSERT INTO Property
(property)
VALUES
('Multiple Properties'),
('animation'),
('animation-delay'),
('animation-direction'),
('animation-duration'),
('animation-fill-mode'),
('animation-iteration-count'),
('animation-name'),
('animation-timing-function'),
('background-color'),
('border'),
('border-collapse'),
('border-color'),
('border-radius'),
('border-spacing'),
('border-style'),
('border-width'),
('bottom'),
('box-shadow'),
('box-sizing'),
('caption-side'),
('color'),
('content'),
('cursor'),
('display'),
('flex-direction'),
('flex-wrap'),
('font-family'),
('font-size'),
('font-style'),
('font-weight'),
('grid-gap'),
('grid-template'),
('height'),
('left'),
('line-height'),
('list-style'),
('margin'),
('margin-bottom'),
('margin-left'),
('margin-right'),
('margin-top'),
('max-height'),
('max-width'),
('min-height'),
('min-width'),
('object-fit'),
('opacity'),
('outline'),
('overflow'),
('padding'),
('padding-bottom'),
('padding-left'),
('padding-right'),
('padding-top'),
('place-content'),
('place-items'),
('place-self'),
('position'),
('right'),
('scroll-behavior'),
('text-align'),
('text-decoration'),
('text-decoration-color'),
('text-decoration-line'),
('text-decoration-style'),
('text-shadow'),
('text-transform'),
('top'),
('transform'),
('transform-origin'),
('transition'),
('vertical-align'),
('width'),
('z-index');

INSERT INTO Variable
(variable)
VALUES
('No Variable'),
('Multiple Variables'),
('--amethyst'),
('--animation-delay'),
('--animation-delay-large'),
('--animation-delay-medium'),
('--animation-delay-small'),
('--animation-direction'),
('--animation-duration'),
('--animation-duration-xs'),
('--animation-duration-sm'),
('--animation-duration-md'),
('--animation-duration-lg'),
('--animation-duration-xl'),
('--animation-fill-mode'),
('--animation-iteration-count'),
('--animation-iteration-count-few'),
('--animation-iteration-count-many'),
('--animation-name'),
('--animation-timing-function'),
('--animation-timing-function-bezier'),
('--animation-timing-function-ease'),
('--animation-timing-function-steps'),
('--article-margin-bottom'),
('--black'),
('--blue'),
('--body-background-color'),
('--body-font-family'),
('--body-font-size'),
('--body-line-height'),
('--body-scroll-behavior'),
('--border-color'),
('--border-radius'),
('--border-radius-circle'),
('--border-radius-round'),
('--border-radius-square'),
('--border-style'),
('--border-width'),
('--border-width-lg'),
('--border-width-md'),
('--border-width-sm'),
('--box-shadow-blur-all'),
('--box-shadow-blur-lg'),
('--box-shadow-blur-md'),
('--box-shadow-blur-sm'),
('--box-shadow-lg'),
('--box-shadow-md'),
('--box-shadow-sm'),
('--box-shadow-spread-all'),
('--box-shadow-spread-lg'),
('--box-shadow-spread-md'),
('--box-shadow-spread-sm'),
('--btn-background-color'),
('--btn-black-border-color'),
('--btn-black-color'),
('--btn-blue-border-color'),
('--btn-blue-color'),
('--btn-border'),
('--btn-border-radius'),
('--btn-checked-transform'),
('--btn-choco-color'),
('--btn-choco-border-color'),
('--btn-circle-border-radius'),
('--btn-circle-sizes'),
('--btn-color'),
('--btn-font-size'),
('--btn-gray-border-color'),
('--btn-gray-color'),
('--btn-green-border-color'),
('--btn-green-color'),
('--btn-hover-animation'),
('--btn-hover-background-color'),
('--btn-hover-border'),
('--btn-hover-border-radius'),
('--btn-hover-color'),
('--btn-hover-box-shadow'),
('--btn-hover-transition'),
('--btn-jade-color'),
('--btn-jade-border-color'),
('--btn-khaki-color'),
('--btn-khaki-border-color'),
('--btn-lg-border-width'),
('--btn-lg-font-size'),
('--btn-lg-padding'),
('--btn-margin'),
('--btn-maroon-border-color'),
('--btn-maroon-color'),
('--btn-md-border-width'),
('--btn-md-padding'),
('--btn-orange-border-color'),
('--btn-orange-color'),
('--btn-padding'),
('--btn-purple-color'),
('--btn-purple-border-color'),
('--btn-red-color'),
('--btn-red-border-color'),
('--btn-round-border-radius'),
('--btn-round-sizes'),
('--btn-salmon-color'),
('--btn-salmon-border-color'),
('--btn-silver-color'),
('--btn-silver-border-color'),
('--btn-sky-color'),
('--btn-sky-border-color'),
('--btn-sm-border-width'),
('--btn-sm-font-size'),
('--btn-sm-padding'),
('--btn-square-border-radius'),
('--btn-square-sizes'),
('--btn-text-align'),
('--btn-tomato-color'),
('--btn-tomato-border-color'),
('--btn-violet-color'),
('--btn-violet-border-color'),
('--btn-white-color'),
('--btn-white-border-color'),
('--btn-yellow-color'),
('--btn-yellow-border-color'),
('--btn-xl-border-width'),
('--btn-xl-font-size'),
('--btn-xl-padding'),
('--btn-xs-border-width'),
('--btn-xs-font-size'),
('--btn-xs-padding'),
('--card-background-color'),
('--card-black-background-color'),
('--card-black-title-box-shadow'),
('--card-black-title-text-shadow'),
('--card-blue-background-color'),
('--card-blue-title-box-shadow'),
('--card-blue-title-text-shadow'),
('--card-border'),
('--card-border-radius'),
('--card-box-shadow'),
('--card-btn-text-align'),
('--card-btn-width'),
('--card-child-background-color'),
('--card-child-border'),
('--card-child-border-radius'),
('--card-child-font-size'),
('--card-child-margin'),
('--card-child-max-width'),
('--card-child-padding'),
('--card-child-text-align'),
('--card-color'),
('--card-flex-direction'),
('--card-green-background-color'),
('--card-green-title-box-shadow'),
('--card-green-title-text-shadow'),
('--card-hover-transform'),
('--card-hover-transition'),
('--card-margin'),
('--card-overflow'),
('--card-padding'),
('--card-place-items'),
('--card-position'),
('--card-purple-background-color'),
('--card-purple-title-box-shadow'),
('--card-purple-title-text-shadow'),
('--card-red-background-color'),
('--card-red-title-box-shadow'),
('--card-red-title-text-shadow'),
('--card-selection-background-color'),
('--card-selection-color'),
('--card-title-box-shadow'),
('--card-title-font-size'),
('--card-title-text-shadow'),
('--card-yellow-background-color'),
('--card-yellow-title-box-shadow'),
('--card-yellow-title-text-shadow'),
('--card-width'),
('--choco'),
('--citrine'),
('--code-font-family'),
('--code-overflow'),
('--code-padding'),
('--code-selection-background-color'),
('--code-selection-color'),
('--column-padding'),
('--emerald'),
('--facebook'),
('--flex-negative-margin-lg'),
('--flex-negative-margin-md'),
('--flex-negative-margin-sm'),
('--flex-negative-margin-xl'),
('--flex-negative-margin-xs'),
('--flex-positive-margin-lg'),
('--flex-positive-margin-md'),
('--flex-positive-margin-sm'),
('--flex-positive-margin-xl'),
('--flex-positive-margin-xs'),
('--flex-width-lg'),
('--flex-width-md'),
('--flex-width-sm'),
('--flex-width-xl'),
('--flex-width-xs'),
('--foot-first-child-background-color'),
('--foot-first-child-cursor'),
('--foot-first-child-flex-direction'),
('--foot-first-child-font-color'),
('--foot-first-child-link-font-color'),
('--foot-first-child-link-hover-font-color'),
('--foot-first-child-link-margin-bottom'),
('--foot-first-child-list-cursor'),
('--foot-first-child-list-text-align'),
('--foot-first-child-margin'),
('--foot-first-child-place-content'),
('--foot-last-child-background-color'),
('--foot-last-child-cursor'),
('--foot-last-child-link-margin-left'),
('--foot-last-child-link-margin-right'),
('--foot-last-child-margin'),
('--foot-last-child-padding-top'),
('--foot-last-child-place-content'),
('--foot-list-padding-bottom'),
('--foot-text-align'),
('--foot-title-color'),
('--foot-title-font-size'),
('--form-action-border'),
('--form-action-box-shadow'),
('--form-action-cursor'),
('--form-action-hover-box-shadow'),
('--form-action-hover-transform'),
('--form-action-hover-transition'),
('--form-action-line-height'),
('--form-action-margin'),
('--form-action-width'),
('--form-border'),
('--form-box-shadow'),
('--form-field-background-color'),
('--form-field-border'),
('--form-field-border-radius'),
('--form-field-box-shadow'),
('--form-field-hover-border'),
('--form-field-hover-box-shadow'),
('--form-field-line-height'),
('--form-field-margin'),
('--form-field-outline'),
('--form-field-padding'),
('--form-field-placeholder-color'),
('--form-field-placeholder-font-style'),
('--form-field-width'),
('--form-fieldset-border'),
('--form-fieldset-margin-left'),
('--form-label-border'),
('--form-label-color'),
('--form-label-hover-border'),
('--form-label-margin'),
('--form-label-padding'),
('--form-label-text-decoration'),
('--form-legend-font-size'),
('--form-legend-font-weight'),
('--form-legend-margin'),
('--form-list-flex-direction'),
('--form-list-place-content'),
('--form-list-place-items'),
('--form-margin'),
('--form-padding'),
('--form-reset-background-color'),
('--form-reset-border'),
('--form-reset-color'),
('--form-reset-hover-background-color'),
('--form-reset-hover-color'),
('--form-submit-background-color'),
('--form-submit-border'),
('--form-submit-color'),
('--form-submit-hover-background-color'),
('--form-submit-hover-color'),
('--form-width'),
('--gallery-all-cursor'),
('--gallery-flex-wrap'),
('--gallery-figcaption-background-color'),
('--gallery-figcaption-bottom'),
('--gallery-figcaption-fa-background-color'),
('--gallery-figcaption-fa-border'),
('--gallery-figcaption-fa-padding'),
('--gallery-figcaption-fa-position'),
('--gallery-figcaption-fa-radius'),
('--gallery-figcaption-fa-right'),
('--gallery-figcaption-fa-top'),
('--gallery-figcaption-line-height'),
('--gallery-figcaption-position'),
('--gallery-figcaption-width'),
('--gallery-figure-border'),
('--gallery-figure-box-shadow'),
('--gallery-figure-hover-figcaption-animation'),
('--gallery-figure-hover-figcaption-bottom'),
('--gallery-figure-line-height'),
('--gallery-figure-margin'),
('--gallery-figure-overflow'),
('--gallery-figure-place-content'),
('--gallery-figure-place-items'),
('--gallery-figure-position'),
('--gallery-figure-width'),
('--gallery-link-all-cursor'),
('--gallery-link-all-margin'),
('--gallery-link-all-even-font-size'),
('--gallery-link-all-even-padding'),
('--gallery-link-all-odd-font-size'),
('--gallery-link-all-odd-padding'),
('--gallery-link-color'),
('--gallery-margin'),
('--gallery-max-width'),
('--gallery-overflow'),
('--gap-1lg'),
('--gap-2lg'),
('--gap-3lg'),
('--gap-1md'),
('--gap-2md'),
('--gap-3md'),
('--gap-1sm'),
('--gap-2sm'),
('--gap-3sm'),
('--gap-1xl'),
('--gap-2xl'),
('--gap-3xl'),
('--gap-1xs'),
('--gap-2xs'),
('--gap-3xs'),
('--github'),
('--gray'),
('--green'),
('--height-lg'),
('--height-md'),
('--height-sm'),
('--img-max-height'),
('--img-max-width'),
('--img-object-fit'),
('--jade'),
('--jsdelivr'),
('--keyframes-content1'),
('--keyframes-content2'),
('--keyframes-content3'),
('--keyframes-content4'),
('--keyframes-content5'),
('--keyframes-rotate'),
('--keyframes-rotateX'),
('--keyframes-rotateY'),
('--keyframes-scale'),
('--keyframes-scaleX'),
('--keyframes-scaleY'),
('--keyframes-skew'),
('--keyframes-skewX'),
('--keyframes-skewY'),
('--keyframes-translate'),
('--keyframes-translateX'),
('--keyframes-translateY'),
('--keyframes-translateY-opac'),
('--keyframes-translateY-xs'),
('--keyframes-width'),
('--khaki'),
('--label-cursor'),
('--linkedin'),
('--link-text-decoration'),
('--link-outline'),
('--list-margin'),
('--list-padding'),
('--list-style'),
('--margin-bottom-lg'),
('--margin-bottom-md'),
('--margin-bottom-sm'),
('--margin-left-lg'),
('--margin-left-md'),
('--margin-left-sm'),
('--margin-lg'),
('--margin-md'),
('--margin-none'),
('--margin-right-lg'),
('--margin-right-md'),
('--margin-right-sm'),
('--margin-sm'),
('--margin-top-lg'),
('--margin-top-md'),
('--margin-top-sm'),
('--maroon'),
('--max-height-lg'),
('--max-height-md'),
('--max-height-sm'),
('--max-width-lg'),
('--max-width-md'),
('--max-width-sm'),
('--menu-all-cursor'),
('--menu-background-color'),
('--menu-border'),
('--menu-border-radius'),
('--menu-checked-label-background-color'),
('--menu-checked-label-color'),
('--menu-checked-label-font-weight'),
('--menu-color'),
('--menu-fa-bottom'),
('--menu-fa-color'),
('--menu-fa-position'),
('--menu-flex-direction'),
('--menu-label-border-radius'),
('--menu-label-hover-background-color'),
('--menu-label-hover-border'),
('--menu-label-hover-color'),
('--menu-label-hover-font-style'),
('--menu-label-padding'),
('--menu-label-place-content'),
('--menu-label-place-items'),
('--menu-label-position'),
('--menu-label-width'),
('--menu-list-style'),
('--menu-margin'),
('--menu-padding'),
('--menu-place-content'),
('--menu-place-items'),
('--menu-width'),
('--min-height-lg'),
('--min-height-md'),
('--min-height-sm'),
('--min-width-lg'),
('--min-width-md'),
('--min-width-sm'),
('--navbar-background-color'),
('--navbar-bottom'),
('--navbar-brand-link-img-height'),
('--navbar-brand-link-left'),
('--navbar-color'),
('--navbar-first-list-link-hover-scale'),
('--navbar-flex-direction'),
('--navbar-height'),
('--navbar-icon-place-self'),
('--navbar-left'),
('--navbar-label-animation'),
('--navbar-label-right'),
('--navbar-label-top'),
('--navbar-last-list-height'),
('--navbar-last-list-img-margin'),
('--navbar-last-list-link-hover-scale'),
('--navbar-link-color'),
('--navbar-link-cursor'),
('--navbar-link-hover-color'),
('--navbar-link-padding'),
('--navbar-list-link-flex-direction'),
('--navbar-list-list-style'),
('--navbar-list-margin'),
('--navbar-list-padding'),
('--navbar-list-place-items'),
('--navbar-padding'),
('--navbar-place-content'),
('--navbar-place-items'),
('--navbar-position'),
('--navbar-right'),
('--navbar-top'),
('--navbar-z-index'),
('--npm'),
('--obsidian'),
('--orange'),
('--padding-bottom-lg'),
('--padding-bottom-md'),
('--padding-bottom-sm'),
('--padding-left-lg'),
('--padding-left-md'),
('--padding-left-sm'),
('--padding-lg'),
('--padding-md'),
('--padding-none'),
('--padding-right-lg'),
('--padding-right-md'),
('--padding-right-sm'),
('--padding-sm'),
('--padding-top-lg'),
('--padding-top-md'),
('--padding-top-sm'),
('--place-content-end'),
('--place-content-start'),
('--place-items-baseline'),
('--place-items-end'),
('--place-items-start'),
('--place-self-baseline'),
('--place-self-end'),
('--place-self-start'),
('--purple'),
('--quartz'),
('--red'),
('--row-padding'),
('--ruby'),
('--salmon'),
('--sapphire'),
('--silver'),
('--sky'),
('--slider-check-direction-animation-direction'),
('--slider-check-direction-list-icon-before-content'),
('--slider-check-play-animation'),
('--slider-check-play-list-icon-before-color'),
('--slider-check-play-list-icon-before-content'),
('--slider-check-repeat-animation-iteration-count'),
('--slider-check-repeat-list-icon-before-content'),
('--slider-figure-margin'),
('--slider-figure-max-height'),
('--slider-figure-max-width'),
('--slider-figure-object-fit'),
('--slider-hover-list-opacity'),
('--slider-icon-color'),
('--slider-list-background-color'),
('--slider-list-border'),
('--slider-list-border-radius'),
('--slider-list-label-color'),
('--slider-list-label-padding'),
('--slider-list-link-color'),
('--slider-list-margin'),
('--slider-list-opacity'),
('--slider-list-padding'),
('--slider-list-place-content'),
('--slider-list-width'),
('--slider-margin'),
('--slider-min-height'),
('--slider-position'),
('--slider-progress-background-color'),
('--slider-progress-height'),
('--slider-radio-list-icon-before-content'),
('--slider-radio1-checked-progress-width'),
('--slider-radio2-checked-progress-width'),
('--slider-radio3-checked-progress-width'),
('--slider-radio4-checked-progress-width'),
('--slider-radio5-checked-progress-width'),
('--slider-text-align'),
('--slider-transition-color'),
('--slider-transition-opacity'),
('--slider-width'),
('--stack-overflow'),
('--table-border-collapse'),
('--table-border-spacing'),
('--table-box-shadow'),
('--table-caption-color'),
('--table-caption-font-size'),
('--table-caption-font-weight'),
('--table-caption-margin-bottom'),
('--table-caption-side'),
('--table-caption-text-shadow'),
('--table-cell-border-color'),
('--table-cell-border-radius'),
('--table-cell-border-style'),
('--table-cell-border-width'),
('--table-cell-cursor'),
('--table-cell-padding'),
('--table-cell-text-align'),
('--table-cell-vertical-align'),
('--table-font-family'),
('--table-margin'),
('--table-margin-bottom'),
('--table-text-align'),
('--table-vertical-align'),
('--table-width'),
('--table-row-even-background-color'),
('--table-row-even-color'),
('--table-row-even-hover-background-color'),
('--table-row-even-hover-box-shadow'),
('--table-row-even-hover-color'),
('--table-row-even-selection-background-color'),
('--table-row-even-selection-color'),
('--table-row-hover-box-shadow'),
('--table-row-odd-background-color'),
('--table-row-odd-color'),
('--table-row-odd-hover-background-color'),
('--table-row-odd-hover-box-shadow'),
('--table-row-odd-hover-color'),
('--table-row-odd-selection-background-color'),
('--table-row-odd-selection-color'),
('--table-title-background-color'),
('--table-title-color'),
('--table-title-font-style'),
('--table-title-selection-background-color'),
('--table-title-selection-color'),
('--text-decoration-color'),
('--text-decoration-line'),
('--text-decoration-style'),
('--text-shadow-blur-all'),
('--text-shadow-blur-lg'),
('--text-shadow-blur-md'),
('--text-shadow-blur-sm'),
('--text-shadow-lg'),
('--text-shadow-md'),
('--text-shadow-sm'),
('--title-font-family'),
('--title-lg-font-size'),
('--title-lg-text-transform'),
('--title-md-font-size'),
('--title-sm-font-size'),
('--title-xl-font-size'),
('--title-xl-text-transform'),
('--title-xs-font-size'),
('--tomato'),
('--transform-origin-near'),
('--transform-origin-far'),
('--twitter'),
('--violet'),
('--white'),
('--width-lg'),
('--width-md'),
('--width-sm'),
('--yellow');

INSERT INTO Class
(class,                 part_id,    source_id,      property_id,    variable_id,    media,      concat,     state)
VALUES
('grid',                '2',        '6',            '1',            '1',            '1',        '1',        '0'),
('fluid',               '2',        '6',            '1',            '1',            '1',        '1',        '0'),
('grid-2xs',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-2xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-3xs',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-3xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-4xs',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-4xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-5xs',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-5xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-6xs',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-6xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-7xs',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-7xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-8xs',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-8xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-9xs',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-9xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-10xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-10xs',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-11xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-11xs',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-12xs',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-12xs',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('gap-1xs',             '2',        '6',            '32',           '317',          '1',        '0',        '0'),
('gap-2xs',             '2',        '6',            '32',           '318',          '1',        '0',        '0'),
('gap-3xs',             '2',        '6',            '32',           '319',          '1',        '0',        '0'),
('grid-2sm',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-2sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-3sm',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-3sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-4sm',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-4sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-5sm',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-5sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-6sm',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-6sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-7sm',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-7sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-8sm',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-8sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-9sm',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-9sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-10sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-10sm',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-11sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-11sm',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-12sm',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-12sm',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('gap-1sm',             '2',        '6',            '32',           '311',          '1',        '0',        '0'),
('gap-2sm',             '2',        '6',            '32',           '312',          '1',        '0',        '0'),
('gap-3sm',             '2',        '6',            '32',           '313',          '1',        '0',        '0'),
('grid-2md',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-2md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-3md',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-3md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-4md',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-4md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-5md',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-5md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-6md',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-6md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-7md',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-7md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-8md',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-8md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-9md',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-9md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-10md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-10md',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-11md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-11md',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-12md',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-12md',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('gap-1md',             '2',        '6',            '32',           '308',          '1',        '0',        '0'),
('gap-2md',             '2',        '6',            '32',           '309',          '1',        '0',        '0'),
('gap-3md',             '2',        '6',            '32',           '310',          '1',        '0',        '0'),
('grid-2lg',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-2lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-3lg',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-3lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-4lg',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-4lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-5lg',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-5lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-6lg',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-6lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-7lg',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-7lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-8lg',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-8lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-9lg',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-9lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-10lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-10lg',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-11lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-11lg',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-12lg',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-12lg',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('gap-1lg',             '2',        '6',            '32',           '305',          '1',        '0',        '0'),
('gap-2lg',             '2',        '6',            '32',           '306',          '1',        '0',        '0'),
('gap-3lg',             '2',        '6',            '32',           '307',          '1',        '0',        '0'),
('grid-2xl',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-2xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-3xl',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-3xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-4xl',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-4xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-5xl',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-5xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-6xl',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-6xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-7xl',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-7xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-8xl',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-8xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-9xl',            '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-9xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-10xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-10xl',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-11xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-11xl',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('grid-12xl',           '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('fluid-12xl',          '2',        '6',            '33',           '1',            '1',        '1',        '0'),
('gap-1xl',             '2',        '6',            '32',           '314',          '1',        '0',        '0'),
('gap-2xl',             '2',        '6',            '32',           '315',          '1',        '0',        '0'),
('gap-3xl',             '2',        '6',            '32',           '316',          '1',        '0',        '0'),
('anima',               '4',        '18',           '1',            '2',            '0',        '1',        '1'),
('anima-rota',          '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-rotax',         '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-rotay',         '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-scal',          '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-scalx',         '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-scaly',         '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-skew',          '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-skewx',         '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-skewy',         '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-tran',          '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-tranx',         '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-trany',         '4',        '18',           '8',            '1',            '0',        '1',        '1'),
('anima-xs',            '4',        '18',           '5',            '10',           '0',        '1',        '1'),
('anima-sm',            '4',        '18',           '5',            '11',           '0',        '1',        '1'),
('anima-md',            '4',        '18',           '5',            '12',           '0',        '1',        '1'),
('anima-lg',            '4',        '18',           '5',            '13',           '0',        '1',        '1'),
('anima-xl',            '4',        '18',           '5',            '14',           '0',        '1',        '1'),
('anima-linear',        '4',        '18',           '9',            '1',            '0',        '1',        '1'),
('anima-ease',          '4',        '18',           '9',            '22',           '0',        '1',        '1'),
('anima-steps',         '4',        '18',           '9',            '23',           '0',        '1',        '1'),
('anima-bezier',        '4',        '18',           '9',            '21',           '0',        '1',        '1'),
('anima-few',           '4',        '18',           '7',            '17',           '0',        '1',        '1'),
('anima-many',          '4',        '18',           '7',            '18',           '0',        '1',        '1'),
('anima-loop',          '4',        '18',           '7',            '1',            '0',        '1',        '1'),
('anima-alter',         '4',        '18',           '4',            '1',            '0',        '1',        '1'),
('anima-rever',         '4',        '18',           '4',            '1',            '0',        '1',        '1'),
('anima-altrev',        '4',        '18',           '4',            '1',            '0',        '1',        '1'),
('anima-small',         '4',        '18',           '3',            '7',            '0',        '1',        '1'),
('anima-medium',        '4',        '18',           '3',            '6',            '0',        '1',        '1'),
('anima-large',         '4',        '18',           '3',            '5',            '0',        '1',        '1'),
('anima-back',          '4',        '18',           '6',            '1',            '0',        '1',        '1'),
('anima-front',         '4',        '18',           '6',            '1',            '0',        '1',        '1'),
('anima-far',           '4',        '18',           '71',           '587',          '0',        '1',        '1'),
('anima-near',          '4',        '18',           '71',           '586',          '0',        '1',        '1'),
('bg-black',            '4',        '19',           '10',           '25',           '0',        '1',        '1'),
('bg-blue',             '4',        '19',           '10',           '26',           '0',        '1',        '1'),
('bg-choco',            '4',        '19',           '10',           '172',          '0',        '1',        '1'),
('bg-gray',             '4',        '19',           '10',           '321',          '0',        '1',        '1'),
('bg-green',            '4',        '19',           '10',           '322',          '0',        '1',        '1'),
('bg-jade',             '4',        '19',           '10',           '329',          '0',        '1',        '1'),
('bg-khaki',            '4',        '19',           '10',           '351',          '0',        '1',        '1'),
('bg-maroon',           '4',        '19',           '10',           '375',          '0',        '1',        '1'),
('bg-orange',           '4',        '19',           '10',           '450',          '0',        '1',        '1'),
('bg-purple',           '4',        '19',           '10',           '475',          '0',        '1',        '1'),
('bg-red',              '4',        '19',           '10',           '477',          '0',        '1',        '1'),
('bg-salmon',           '4',        '19',           '10',           '480',          '0',        '1',        '1'),
('bg-silver',           '4',        '19',           '10',           '482',          '0',        '1',        '1'),
('bg-sky',              '4',        '19',           '10',           '483',          '0',        '1',        '1'),
('bg-tomato',           '4',        '19',           '10',           '585',          '0',        '1',        '1'),
('bg-violet',           '4',        '19',           '10',           '589',          '0',        '1',        '1'),
('bg-white',            '4',        '19',           '10',           '590',          '0',        '1',        '1'),
('bg-yellow',           '4',        '19',           '10',           '594',          '0',        '1',        '1'),
('bg-fb',               '4',        '19',           '10',           '181',          '0',        '1',        '1'),
('bg-github',           '4',        '19',           '10',           '320',          '0',        '1',        '1'),
('bg-jsd',              '4',        '19',           '10',           '330',          '0',        '1',        '1'),
('bg-linkedin',         '4',        '19',           '10',           '353',          '0',        '1',        '1'),
('bg-npm',              '4',        '19',           '10',           '448',          '0',        '1',        '1'),
('bg-stack',            '4',        '19',           '10',           '523',          '0',        '1',        '1'),
('bg-tw',               '4',        '19',           '10',           '588',          '0',        '1',        '1'),
('amethyst',            '4',        '19',           '10',           '3',            '0',        '1',        '1'),
('citrine',             '4',        '19',           '10',           '173',          '0',        '1',        '1'),
('emerald',             '4',        '19',           '10',           '180',          '0',        '1',        '1'),
('quartz',              '4',        '19',           '10',           '476',          '0',        '1',        '1'),
('obsidian',            '4',        '19',           '10',           '449',          '0',        '1',        '1'),
('ruby',                '4',        '19',           '10',           '479',          '0',        '1',        '1'),
('sapphire',            '4',        '19',           '10',           '481',          '0',        '1',        '1'),
('bord',                '4',        '20',           '1',            '2',            '0',        '1',        '1'),
('bord-dash',           '4',        '20',           '16',           '1',            '0',        '1',        '1'),
('bord-dot',            '4',        '20',           '16',           '1',            '0',        '1',        '1'),
('bord-double',         '4',        '20',           '16',           '1',            '0',        '1',        '1'),
('bord-groove',         '4',        '20',           '16',           '1',            '0',        '1',        '1'),
('bord-inset',          '4',        '20',           '16',           '1',            '0',        '1',        '1'),
('bord-outset',         '4',        '20',           '16',           '1',            '0',        '1',        '1'),
('bord-ridge',          '4',        '20',           '16',           '1',            '0',        '1',        '1'),
('bord-solid',          '4',        '20',           '16',           '1',            '0',        '1',        '1'),
('bord-sm',             '4',        '20',           '17',           '41',           '0',        '1',        '1'),
('bord-md',             '4',        '20',           '17',           '40',           '0',        '1',        '1'),
('bord-lg',             '4',        '20',           '17',           '39',           '0',        '1',        '1'),
('bord-black',          '4',        '20',           '13',           '25',           '0',        '1',        '1'),
('bord-blue',           '4',        '20',           '13',           '26',           '0',        '1',        '1'),
('bord-gray',           '4',        '20',           '13',           '321',          '0',        '1',        '1'),
('bord-green',          '4',        '20',           '13',           '322',          '0',        '1',        '1'),
('bord-maroon',         '4',        '20',           '13',           '375',          '0',        '1',        '1'),
('bord-orange',         '4',        '20',           '13',           '450',          '0',        '1',        '1'),
('bord-purple',         '4',        '20',           '13',           '475',          '0',        '1',        '1'),
('bord-red',            '4',        '20',           '13',           '477',          '0',        '1',        '1'),
('bord-white',          '4',        '20',           '13',           '590',          '0',        '1',        '1'),
('bord-yellow',         '4',        '20',           '13',           '594',          '0',        '1',        '1'),
('bord-circle',         '4',        '20',           '14',           '34',           '0',        '1',        '1'),
('bord-round',          '4',        '20',           '14',           '35',           '0',        '1',        '1'),
('bord-square',         '4',        '20',           '14',           '36',           '0',        '1',        '1'),
('color-black',         '4',        '21',           '22',           '25',           '0',        '1',        '1'),
('color-blue',          '4',        '21',           '22',           '26',           '0',        '1',        '1'),
('color-choco',         '4',        '21',           '22',           '172',          '0',        '1',        '1'),
('color-gray',          '4',        '21',           '22',           '321',          '0',        '1',        '1'),
('color-green',         '4',        '21',           '22',           '322',          '0',        '1',        '1'),
('color-jade',          '4',        '21',           '22',           '329',          '0',        '1',        '1'),
('color-khaki',         '4',        '21',           '22',           '351',          '0',        '1',        '1'),
('color-maroon',        '4',        '21',           '22',           '375',          '0',        '1',        '1'),
('color-orange',        '4',        '21',           '22',           '450',          '0',        '1',        '1'),
('color-purple',        '4',        '21',           '22',           '475',          '0',        '1',        '1'),
('color-red',           '4',        '21',           '22',           '477',          '0',        '1',        '1'),
('color-salmon',        '4',        '21',           '22',           '480',          '0',        '1',        '1'),
('color-silver',        '4',        '21',           '22',           '482',          '0',        '1',        '1'),
('color-sky',           '4',        '21',           '22',           '483',          '0',        '1',        '1'),
('color-tomato',        '4',        '21',           '22',           '585',          '0',        '1',        '1'),
('color-violet',        '4',        '21',           '22',           '589',          '0',        '1',        '1'),
('color-white',         '4',        '21',           '22',           '590',          '0',        '1',        '1'),
('color-yellow',        '4',        '21',           '22',           '594',          '0',        '1',        '1'),
('color-fb',            '4',        '21',           '22',           '181',          '0',        '1',        '1'),
('color-github',        '4',        '21',           '22',           '320',          '0',        '1',        '1'),
('color-jsd',           '4',        '21',           '22',           '330',          '0',        '1',        '1'),
('color-linkedin',      '4',        '21',           '22',           '353',          '0',        '1',        '1'),
('color-npm',           '4',        '21',           '22',           '448',          '0',        '1',        '1'),
('color-stack',         '4',        '21',           '22',           '523',          '0',        '1',        '1'),
('color-tw',            '4',        '21',           '22',           '588',          '0',        '1',        '1'),
('deco',                '4',        '22',           '1',            '2',            '0',        '1',        '1'),
('deco-none',           '4',        '22',           '65',           '1',            '0',        '1',        '1'),
('deco-under',          '4',        '22',           '65',           '1',            '0',        '1',        '1'),
('deco-through',        '4',        '22',           '65',           '1',            '0',        '1',        '1'),
('deco-over',           '4',        '22',           '65',           '1',            '0',        '1',        '1'),
('deco-solid',          '4',        '22',           '66',           '1',            '0',        '1',        '1'),
('deco-double',         '4',        '22',           '66',           '1',            '0',        '1',        '1'),
('deco-dash',           '4',        '22',           '66',           '1',            '0',        '1',        '1'),
('deco-dot',            '4',        '22',           '66',           '1',            '0',        '1',        '1'),
('deco-wavy',           '4',        '22',           '66',           '1',            '0',        '1',        '1'),
('deco-black',          '4',        '22',           '64',           '25',           '0',        '1',        '1'),
('deco-blue',           '4',        '22',           '64',           '26',           '0',        '1',        '1'),
('deco-gray',           '4',        '22',           '64',           '321',          '0',        '1',        '1'),
('deco-green',          '4',        '22',           '64',           '322',          '0',        '1',        '1'),
('deco-maroon',         '4',        '22',           '64',           '375',          '0',        '1',        '1'),
('deco-orange',         '4',        '22',           '64',           '450',          '0',        '1',        '1'),
('deco-purple',         '4',        '22',           '64',           '475',          '0',        '1',        '1'),
('deco-red',            '4',        '22',           '64',           '477',          '0',        '1',        '1'),
('deco-white',          '4',        '22',           '64',           '590',          '0',        '1',        '1'),
('deco-yellow',         '4',        '22',           '64',           '594',          '0',        '1',        '1'),
('block-xs',            '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('block-sm',            '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('block-md',            '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('block-lg',            '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('block-xl',            '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('hide-xs',             '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('hide-sm',             '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('hide-md',             '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('hide-lg',             '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('hide-xl',             '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('inline-xs',           '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('inline-sm',           '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('inline-md',           '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('inline-lg',           '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('inline-xl',           '4',        '23',           '25',           '1',            '1',        '1',        '1'),
('absolute-xs',         '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('absolute-sm',         '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('absolute-md',         '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('absolute-lg',         '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('absolute-xl',         '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('fixed-xs',            '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('fixed-sm',            '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('fixed-md',            '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('fixed-lg',            '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('fixed-xl',            '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('relative-xs',         '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('relative-sm',         '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('relative-md',         '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('relative-lg',         '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('relative-xl',         '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('sticky-xs',           '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('sticky-sm',           '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('sticky-md',           '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('sticky-lg',           '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('sticky-xl',           '4',        '24',           '59',           '1',            '1',        '1',        '1'),
('pos-top',             '4',        '24',           '1',            '1',            '0',        '1',        '1'),
('pos-bot',             '4',        '24',           '1',            '1',            '0',        '1',        '1'),
('pos-right',           '4',        '24',           '1',            '1',            '0',        '1',        '1'),
('pos-left',            '4',        '24',           '1',            '1',            '0',        '1',        '1'),
('shabox-sm',           '4',        '25',           '19',           '48',           '0',        '1',        '1'),
('shabox-in-sm',        '4',        '25',           '19',           '48',           '0',        '1',        '1'),
('shabox-md',           '4',        '25',           '19',           '47',           '0',        '1',        '1'),
('shabox-in-md',        '4',        '25',           '19',           '47',           '0',        '1',        '1'),
('shabox-lg',           '4',        '25',           '19',           '46',           '0',        '1',        '1'),
('shabox-in-lg',        '4',        '25',           '19',           '46',           '0',        '1',        '1'),
('shabox-blur-all',     '4',        '25',           '19',           '42',           '0',        '1',        '1'),
('shabox-in-blur-all',  '4',        '25',           '19',           '42',           '0',        '1',        '1'),
('shabox-blur-sm',      '4',        '25',           '19',           '45',           '0',        '1',        '1'),
('shabox-in-blur-sm',   '4',        '25',           '19',           '45',           '0',        '1',        '1'),
('shabox-blur-md',      '4',        '25',           '19',           '44',           '0',        '1',        '1'),
('shabox-in-blur-md',   '4',        '25',           '19',           '44',           '0',        '1',        '1'),
('shabox-blur-lg',      '4',        '25',           '19',           '43',           '0',        '1',        '1'),
('shabox-in-blur-lg',   '4',        '25',           '19',           '43',           '0',        '1',        '1'),
('shabox-spread-all',   '4',        '25',           '19',           '49',           '0',        '1',        '1'),
('shabox-in-spread-all','4',        '25',           '19',           '49',           '0',        '1',        '1'),
('shabox-spread-sm',    '4',        '25',           '19',           '52',           '0',        '1',        '1'),
('shabox-in-spread-sm', '4',        '25',           '19',           '52',           '0',        '1',        '1'),
('shabox-spread-md',    '4',        '25',           '19',           '51',           '0',        '1',        '1'),
('shabox-in-spread-md', '4',        '25',           '19',           '51',           '0',        '1',        '1'),
('shabox-spread-lg',    '4',        '25',           '19',           '50',           '0',        '1',        '1'),
('shabox-in-spread-lg', '4',        '25',           '19',           '50',           '0',        '1',        '1'),
('shatex-sm',           '4',        '26',           '67',           '576',          '0',        '1',        '1'),
('shatex-md',           '4',        '26',           '67',           '575',          '0',        '1',        '1'),
('shatex-lg',           '4',        '26',           '67',           '574',          '0',        '1',        '1'),
('shatex-blur-all',     '4',        '26',           '67',           '570',          '0',        '1',        '1'),
('shatex-blur-sm',      '4',        '26',           '67',           '573',          '0',        '1',        '1'),
('shatex-blur-md',      '4',        '26',           '67',           '572',          '0',        '1',        '1'),
('shatex-blur-lg',      '4',        '26',           '67',           '571',          '0',        '1',        '1');
