USE animadio;

CREATE TABLE StatesProperty
(
    id          TINYINT     UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    property    VARCHAR(30) NOT NULL    UNIQUE
)
    ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO StatesProperty
(property)
VALUES
('animation-name'),
('animation-duration'),
('animation-timing-function'),
('animation-iteration-count'),
('animation-delay'),
('animation-direction'),
('animation-fill-mode'),
('display'),
('position'),
('background-color'),
('color');

CREATE TABLE States
(
    id          SMALLINT        UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    class       VARCHAR(20)     NOT NULL    UNIQUE,
    valor       VARCHAR(40)     NOT NULL,
    property    TINYINT         UNSIGNED    NOT NULL,
    source      TINYINT         UNSIGNED    NOT NULL,
    media       TINYINT         UNSIGNED    NOT NULL,
    concat      TINYINT(1)      NOT NULL,
    CONSTRAINT  states_property FOREIGN KEY (property)  REFERENCES  StatesProperty(id)
)
    ENGINE=INNODB DEFAULT CHARSET=UTF8;


INSERT INTO States
(class,                 valor,                                  property,   source, media,  concat)
VALUES
('anima-',              '--animation-duration',                 2,          1,      1,      0),
('anima-bounce',        'bounce',                               1,          1,      1,      0),
('anima-flipperX',      'flipperX',                             1,          1,      1,      0),
('anima-flipperY',      'flipperY',                             1,          1,      1,      0),
('anima-openX',         'openX',                                1,          1,      1,      0),
('anima-openY',         'openY',                                1,          1,      1,      0),
('anima-flipX',         'flipX',                                1,          1,      1,      0),
('anima-flipY',         'flipY',                                1,          1,      1,      0),
('anima-fallX',         'fallX',                                1,          1,      1,      0),
('anima-fallY',         'fallY',                                1,          1,      1,      0),
('anima-grow',          'grow',                                 1,          1,      1,      0),
('anima-growX',         'growX',                                1,          1,      1,      0),
('anima-growY',         'growY',                                1,          1,      1,      0),
('anima-shrink',        'shrink',                               1,          1,      1,      0),
('anima-shrinkX',       'shrinkX',                              1,          1,      1,      0),
('anima-shrinkY',       'shrinkY',                              1,          1,      1,      0),
('anima-twistT',        'twistT',                               1,          1,      1,      0),
('anima-twistR',        'twistR',                               1,          1,      1,      0),
('anima-twistB',        'twistB',                               1,          1,      1,      0),
('anima-twistL',        'twistL',                               1,          1,      1,      0),
('anima-torsionT',      'torsionT',                             1,          1,      1,      0),
('anima-torsionR',      'torsionR',                             1,          1,      1,      0),
('anima-torsionB',      'torsionB',                             1,          1,      1,      0),
('anima-torsionL',      'torsionL',                             1,          1,      1,      0),
('anima-twisterT',      'twisterT',                             1,          1,      1,      0),
('anima-twisterR',      'twisterR',                             1,          1,      1,      0),
('anima-twisterB',      'twisterB',                             1,          1,      1,      0),
('anima-twisterL',      'twisterL',                             1,          1,      1,      0),
('anima-cycloneT',      'cycloneT',                             1,          1,      1,      0),
('anima-cycloneR',      'cycloneR',                             1,          1,      1,      0),
('anima-cycloneB',      'cycloneB',                             1,          1,      1,      0),
('anima-cycloneL',      'cycloneL',                             1,          1,      1,      0),
('anima-half',          'half',                                 1,          1,      1,      0),
('anima-halfX',         'halfX',                                1,          1,      1,      0),
('anima-halfY',         'halfY',                                1,          1,      1,      0),
('anima-halfXY',        'halfXY',                               1,          1,      1,      0),
('anima-halfXZ',        'halfXZ',                               1,          1,      1,      0),
('anima-halfYZ',        'halfYZ',                               1,          1,      1,      0),
('anima-half3D',        'half3D',                               1,          1,      1,      0),
('anima-full',          'full',                                 1,          1,      1,      0),
('anima-fullX',         'fullX',                                1,          1,      1,      0),
('anima-fullY',         'fullY',                                1,          1,      1,      0),
('anima-fullXY',        'fullXY',                               1,          1,      1,      0),
('anima-fullXZ',        'fullXZ',                               1,          1,      1,      0),
('anima-fullYZ',        'fullYZ',                               1,          1,      1,      0),
('anima-full3D',        'full3D',                               1,          1,      1,      0),
('anima-slipT',         'slipT',                                1,          1,      1,      0),
('anima-slipR',         'slipR',                                1,          1,      1,      0),
('anima-slipB',         'slipB',                                1,          1,      1,      0),
('anima-slipL',         'slipL',                                1,          1,      1,      0),
('anima-slipTR',        'slipTR',                               1,          1,      1,      0),
('anima-slipBR',        'slipBR',                               1,          1,      1,      0),
('anima-slipBL',        'slipBL',                               1,          1,      1,      0),
('anima-slipTL',        'slipTL',                               1,          1,      1,      0),
('anima-slideT',        'slideT',                               1,          1,      1,      0),
('anima-slideR',        'slideR',                               1,          1,      1,      0),
('anima-slideB',        'slideB',                               1,          1,      1,      0),
('anima-slideL',        'slideL',                               1,          1,      1,      0),
('anima-slideTR',       'slideTR',                              1,          1,      1,      0),
('anima-slideBR',       'slideBR',                              1,          1,      1,      0),
('anima-slideBL',       'slideBL',                              1,          1,      1,      0),
('anima-slideTL',       'slideTL',                              1,          1,      1,      0),
('anima-tn',            '--animation-duration-tn',              2,          1,      1,      0),
('anima-sm',            '--animation-duration-sm',              2,          1,      1,      0),
('anima-md',            '--animation-duration-md',              2,          1,      1,      0),
('anima-lg',            '--animation-duration-lg',              2,          1,      1,      0),
('anima-wd',            '--animation-duration-wd',              2,          1,      1,      0),
('anima-linear',        '--animation-timing-function-linear',   3,          1,      1,      0),
('anima-in',            '--animation-timing-function-in',       3,          1,      1,      0),
('anima-out',           '--animation-timing-function-out',      3,          1,      1,      0),
('anima-inout',         '--animation-timing-function-inout',    3,          1,      1,      0),
('anima-bezier',        '--animation-timing-function-bezier',   3,          1,      1,      0),
('anima-start',         '--animation-timing-function-start',    3,          1,      1,      0),
('anima-end',           '--animation-timing-function-end',      3,          1,      1,      0),
('anima-chrono',        '--animation-timing-function-chrono',   3,          1,      1,      0),
('anima-timer',         '--animation-timing-function-timer',    3,          1,      1,      0),
('anima-few',           '--animation-iteration-count-few',      4,          1,      1,      0),
('anima-many',          '--animation-iteration-count-many',     4,          1,      1,      0),
('anima-loop',          '--animation-iteration-count-loop',     4,          1,      1,      0),
('anima-small',         '--animation-delay-small',              5,          1,      1,      0),
('anima-medium',        '--animation-delay-medium',             5,          1,      1,      0),
('anima-large',         '--animation-delay-large',              5,          1,      1,      0),
('anima-alt',           'alternate',                            6,          1,      1,      0),
('anima-rev',           'reverse',                              6,          1,      1,      0),
('anima-altrev',        'alternate-reverse',                    6,          1,      1,      0),
('anima-front',         'forwards',                             7,          1,      1,      0),
('anima-back',          'backwards',                            7,          1,      1,      0),
('anima-both',          'both',                                 7,          1,      1,      0),
('hide',                'none',                                 8,          2,      1,      0),
('hide-sm',             'none',                                 8,          2,      2,      0),
('hide-md',             'none',                                 8,          2,      3,      0),
('hide-lg',             'none',                                 8,          2,      4,      0),
('hide-wd',             'none',                                 8,          2,      5,      0),
('inline',              'inline',                               8,          2,      1,      0),
('inline-sm',           'inline',                               8,          2,      2,      0),
('inline-md',           'inline',                               8,          2,      3,      0),
('inline-lg',           'inline',                               8,          2,      4,      0),
('inline-wd',           'inline',                               8,          2,      5,      0),
('block',               'block',                                8,          2,      1,      0),
('block-sm',            'block',                                8,          2,      2,      0),
('block-md',            'block',                                8,          2,      3,      0),
('block-lg',            'block',                                8,          2,      4,      0),
('block-wd',            'block',                                8,          2,      5,      0),
('inblock',             'inline-block',                         8,          2,      1,      0),
('inblock-sm',          'inline-block',                         8,          2,      2,      0),
('inblock-md',          'inline-block',                         8,          2,      3,      0),
('inblock-lg',          'inline-block',                         8,          2,      4,      0),
('inblock-wd',          'inline-block',                         8,          2,      5,      0),
('absolute',            'absolute',                             9,          3,      1,      0),
('absolute-sm',         'absolute',                             9,          3,      2,      0),
('absolute-md',         'absolute',                             9,          3,      3,      0),
('absolute-lg',         'absolute',                             9,          3,      4,      0),
('absolute-wd',         'absolute',                             9,          3,      5,      0),
('fixed',               'fixed',                                9,          3,      1,      0),
('fixed-sm',            'fixed',                                9,          3,      2,      0),
('fixed-md',            'fixed',                                9,          3,      3,      0),
('fixed-lg',            'fixed',                                9,          3,      4,      0),
('fixed-wd',            'fixed',                                9,          3,      5,      0),
('relative',            'relative',                             9,          3,      1,      0),
('relative-sm',         'relative',                             9,          3,      2,      0),
('relative-md',         'relative',                             9,          3,      3,      0),
('relative-lg',         'relative',                             9,          3,      4,      0),
('relative-wd',         'relative',                             9,          3,      5,      0),
('sticky-tn',           'sticky',                               9,          3,      1,      0),
('sticky-sm',           'sticky',                               9,          3,      2,      0),
('sticky-md',           'sticky',                               9,          3,      3,      0),
('sticky-lg',           'sticky',                               9,          3,      4,      0),
('sticky-wd',           'sticky',                               9,          3,      5,      0),
('bg-magenta',          '--magenta',                            10,         4,      1,      0),
('bg-red',              '--red',                                10,         4,      1,      0),
('bg-orange',           '--orange',                             10,         4,      1,      0),
('bg-gold',             '--gold',                               10,         4,      1,      0),
('bg-maroon',           '--maroon',                             10,         4,      1,      0),
('bg-green',            '--green',                              10,         4,      1,      0),
('bg-blue',             '--blue',                               10,         4,      1,      0),
('bg-navy',             '--navy',                               10,         4,      1,      0),
('bg-purple',           '--purple',                             10,         4,      1,      0),
('bg-gray',             '--gray',                               10,         4,      1,      0),
('bg-pink',             '--pink',                               10,         4,      1,      0),
('bg-tomato',           '--tomato',                             10,         4,      1,      0),
('bg-coral',            '--coral',                              10,         4,      1,      0),
('bg-yellow',           '--yellow',                             10,         4,      1,      0),
('bg-brown',            '--brown',                              10,         4,      1,      0),
('bg-aqua',             '--aqua',                               10,         4,      1,      0),
('bg-cyan',             '--cyan',                               10,         4,      1,      0),
('bg-sky',              '--sky',                                10,         4,      1,      0),
('bg-violet',           '--violet',                             10,         4,      1,      0),
('bg-silver',           '--silver',                             10,         4,      1,      0),
('bg-fb',               '--fb',                                 10,         4,      1,      0),
('bg-gh',               '--gh',                                 10,         4,      1,      0),
('bg-in',               '--in',                                 10,         4,      1,      0),
('bg-pp',               '--pp',                                 10,         4,      1,      0),
('bg-tw',               '--tw',                                 10,         4,      1,      0),
('bg-magenta-dark',     '--magenta-dark',                       10,         4,      1,      0),
('bg-red-dark',         '--red-dark',                           10,         4,      1,      0),
('bg-orange-dark',      '--orange-dark',                        10,         4,      1,      0),
('bg-gold-dark',        '--gold-dark',                          10,         4,      1,      0),
('bg-maroon-dark',      '--maroon-dark',                        10,         4,      1,      0),
('bg-green-dark',       '--green-dark',                         10,         4,      1,      0),
('bg-blue-dark',        '--blue-dark',                          10,         4,      1,      0),
('bg-navy-dark',        '--navy-dark',                          10,         4,      1,      0),
('bg-purple-dark',      '--purple-dark',                        10,         4,      1,      0),
('bg-gray-dark',        '--gray-dark',                          10,         4,      1,      0),
('bg-pink-dark',        '--pink-dark',                          10,         4,      1,      0),
('bg-tomato-dark',      '--tomato-dark',                        10,         4,      1,      0),
('bg-coral-dark',       '--coral-dark',                         10,         4,      1,      0),
('bg-yellow-dark',      '--yellow-dark',                        10,         4,      1,      0),
('bg-brown-dark',       '--brown-dark',                         10,         4,      1,      0),
('bg-aqua-dark',        '--aqua-dark',                          10,         4,      1,      0),
('bg-cyan-dark',        '--cyan-dark',                          10,         4,      1,      0),
('bg-sky-dark',         '--sky-dark',                           10,         4,      1,      0),
('bg-violet-dark',      '--violet-dark',                        10,         4,      1,      0),
('bg-silver-dark',      '--silver-dark',                        10,         4,      1,      0),
('bg-magenta-light',    '--magenta-light',                      10,         4,      1,      0),
('bg-red-light',        '--red-light',                          10,         4,      1,      0),
('bg-orange-light',     '--orange-light',                       10,         4,      1,      0),
('bg-gold-light',       '--gold-light',                         10,         4,      1,      0),
('bg-maroon-light',     '--maroon-light',                       10,         4,      1,      0),
('bg-green-light',      '--green-light',                        10,         4,      1,      0),
('bg-blue-light',       '--blue-light',                         10,         4,      1,      0),
('bg-navy-light',       '--navy-light',                         10,         4,      1,      0),
('bg-purple-light',     '--purple-light',                       10,         4,      1,      0),
('bg-gray-light',       '--gray-light',                         10,         4,      1,      0),
('bg-pink-light',       '--pink-light',                         10,         4,      1,      0),
('bg-tomato-light',     '--tomato-light',                       10,         4,      1,      0),
('bg-coral-light',      '--coral-light',                        10,         4,      1,      0),
('bg-yellow-light',     '--yellow-light',                       10,         4,      1,      0),
('bg-brown-light',      '--brown-light',                        10,         4,      1,      0),
('bg-aqua-light',       '--aqua-light',                         10,         4,      1,      0),
('bg-cyan-light',       '--cyan-light',                         10,         4,      1,      0),
('bg-sky-light',        '--sky-light',                          10,         4,      1,      0),
('bg-violet-light',     '--violet-light',                       10,         4,      1,      0),
('bg-silver-light',     '--silver-light',                       10,         4,      1,      0),
('color-magenta',       '--magenta',                            11,         5,      1,      0),
('color-red',           '--red',                                11,         5,      1,      0),
('color-orange',        '--orange',                             11,         5,      1,      0),
('color-gold',          '--gold',                               11,         5,      1,      0),
('color-maroon',        '--maroon',                             11,         5,      1,      0),
('color-green',         '--green',                              11,         5,      1,      0),
('color-blue',          '--blue',                               11,         5,      1,      0),
('color-navy',          '--navy',                               11,         5,      1,      0),
('color-purple',        '--purple',                             11,         5,      1,      0),
('color-gray',          '--gray',                               11,         5,      1,      0),
('color-pink',          '--pink',                               11,         5,      1,      0),
('color-tomato',        '--tomato',                             11,         5,      1,      0),
('color-coral',         '--coral',                              11,         5,      1,      0),
('color-yellow',        '--yellow',                             11,         5,      1,      0),
('color-brown',         '--brown',                              11,         5,      1,      0),
('color-aqua',          '--aqua',                               11,         5,      1,      0),
('color-cyan',          '--cyan',                               11,         5,      1,      0),
('color-sky',           '--sky',                                11,         5,      1,      0),
('color-violet',        '--violet',                             11,         5,      1,      0),
('color-silver',        '--silver',                             11,         5,      1,      0),
('color-fb',            '--fb',                                 11,         5,      1,      0),
('color-gh',            '--gh',                                 11,         5,      1,      0),
('color-in',            '--in',                                 11,         5,      1,      0),
('color-pp',            '--pp',                                 11,         5,      1,      0),
('color-tw',            '--tw',                                 11,         5,      1,      0),
('color-magenta-dark',  '--magenta-dark',                       11,         5,      1,      0),
('color-red-dark',      '--red-dark',                           11,         5,      1,      0),
('color-orange-dark',   '--orange-dark',                        11,         5,      1,      0),
('color-gold-dark',     '--gold-dark',                          11,         5,      1,      0),
('color-maroon-dark',   '--maroon-dark',                        11,         5,      1,      0),
('color-green-dark',    '--green-dark',                         11,         5,      1,      0),
('color-blue-dark',     '--blue-dark',                          11,         5,      1,      0),
('color-navy-dark',     '--navy-dark',                          11,         5,      1,      0),
('color-purple-dark',   '--purple-dark',                        11,         5,      1,      0),
('color-gray-dark',     '--gray-dark',                          11,         5,      1,      0),
('color-pink-dark',     '--pink-dark',                          11,         5,      1,      0),
('color-tomato-dark',   '--tomato-dark',                        11,         5,      1,      0),
('color-coral-dark',    '--coral-dark',                         11,         5,      1,      0),
('color-yellow-dark',   '--yellow-dark',                        11,         5,      1,      0),
('color-brown-dark',    '--brown-dark',                         11,         5,      1,      0),
('color-aqua-dark',     '--aqua-dark',                          11,         5,      1,      0),
('color-cyan-dark',     '--cyan-dark',                          11,         5,      1,      0),
('color-sky-dark',      '--sky-dark',                           11,         5,      1,      0),
('color-violet-dark',   '--violet-dark',                        11,         5,      1,      0),
('color-silver-dark',   '--silver-dark',                        11,         5,      1,      0),
('color-magenta-light', '--magenta-light',                      11,         5,      1,      0),
('color-red-light',     '--red-light',                          11,         5,      1,      0),
('color-orange-light',  '--orange-light',                       11,         5,      1,      0),
('color-gold-light',    '--gold-light',                         11,         5,      1,      0),
('color-maroon-light',  '--maroon-light',                       11,         5,      1,      0),
('color-green-light',   '--green-light',                        11,         5,      1,      0),
('color-blue-light',    '--blue-light',                         11,         5,      1,      0),
('color-navy-light',    '--navy-light',                         11,         5,      1,      0),
('color-purple-light',  '--purple-light',                       11,         5,      1,      0),
('color-gray-light',    '--gray-light',                         11,         5,      1,      0),
('color-pink-light',    '--pink-light',                         11,         5,      1,      0),
('color-tomato-light',  '--tomato-light',                       11,         5,      1,      0),
('color-coral-light',   '--coral-light',                        11,         5,      1,      0),
('color-yellow-light',  '--yellow-light',                       11,         5,      1,      0),
('color-brown-light',   '--brown-light',                        11,         5,      1,      0),
('color-aqua-light',    '--aqua-light',                         11,         5,      1,      0),
('color-cyan-light',    '--cyan-light',                         11,         5,      1,      0),
('color-sky-light',     '--sky-light',                          11,         5,      1,      0),
('color-violet-light',  '--violet-light',                       11,         5,      1,      0),
('color-silver-light',  '--silver-light',                       11,         5,      1,      0);
